Bug/#87 backButton이 잘 눌리지 않는 현상 수정 및 의견 쓰기 페이지 리팩토링
Neupinion/Neupinion-App pull request #111
Opened 2024-05-30 13:59 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 원인: 커스텀 헤더를 사용할 경우, Navigation 헤더에 직접 적용하지 않으면 Svg이미지가 잘 눌리지 않음.
- 해결: 커스텀 헤더를 재작성 후, Navigation헤더에 직접 적용, 버튼 잘 눌림.
- 리팩토링: 

커스텀 헤더를 통해, 헤더에 적용된 버튼을 상위 컴포넌트에 직접 적용해야하는 상황이였습니다.
OpinionPostPage, OpinionPinPage의 상태가 너무 복잡하게 작성되어있어, recoil의 atom을 이용해 전역 상태관리를 이용하기로 하였고, 북마크 기능 또한 컴포넌트 분리하였습니다.

- 참고: 앱 링크 공유 기능을 임시로 적용하였습니다. 재가공이슈 우측 상단을 누르면 카카오톡 앱스토어나 플레이스토어로 연결 가능한 링크가 적용되어있습니다. Navigation.tsx에서 헤더와 관련된 정보를 작성하도록 하였습니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #87

2024-05-30 15:08 UTC, Cyma-s requested changes
간단한 변경 리뷰만 남겼습니다!

2024-05-30 15:08 UTC, Cyma-s commented on src/pages/ReprocessedIssueDetailPage.tsx
> +  const setBookMarkState = useSetRecoilState<bookMarkInfo>(bookMarkState);
bookmark 가 맞는 단어더라고요 
지금 시간 없으시면 나중에 bookmark 로 수정해주세요!

2024-05-31 00:36 UTC, hayeounglee approved these changes
수고 많으셨습니다!!!

2024-05-31 00:36 UTC, hayeounglee commented on src/Navigation.tsx
> +              options={({
options를 통해 각 화면의 제목, 헤더 스타일, 헤더 표시 여부 등 다양한 설정을 커스터마이즈하셨군요!
이제 PageHeader 없이 이런식으로 관리되는건가요?

2024-05-31 00:36 UTC, hayeounglee commented on src/Navigation.tsx
> +              options={({
네비게이션을 이렇게 바꾼 이유가 전에 백버튼 작동이 잘 안되서 인가요?

2024-05-31 00:36 UTC, hayeounglee commented on src/Navigation.tsx
> +                        key="check"
key값은 무엇을 하나요?

2024-05-31 00:36 UTC, hayeounglee commented on src/features/opinion/components/OpinionPostCheckButton.tsx
> +  const opinionPost = useRecoilValue(opinionPostState);
이런식으로 변수의 상태를 관리하는 군요! 👍
이걸 통해 전역으로 변수를 관리하는게 맞나요?

2024-05-31 00:36 UTC, hayeounglee commented on src/features/opinion/components/OpinionPostCheckButton.tsx
> +    if (activity == 'OpinionPost' && !isLoading) {
activity가 opinoinPost 또는 OpinionPin일떄는
무슨 상황인가요?

2024-05-31 00:36 UTC, hayeounglee commented on src/features/opinion/components/OpinionPostCheckButton.tsx
> +    if (activity == 'OpinionPin') {
if (activity == 'OpinionPost' && !isLoading) 와 !isLoading인 경우는 필요 없나요?

2024-05-31 00:36 UTC, hayeounglee commented on src/recoil/opinionPostState.ts
> +    opinionId: 0,
디폴트 값으로 issueId, opinionId를 null, undefined이 아니라 0으로 해도 되나요?

2024-05-31 01:55 UTC, dmstjdhdh commented on src/Navigation.tsx
> +                    title="진짜일까, 가짜일까?"
넵 맞습니다. 해당 타이틀은, 앱 맨 위쪽에 나타나는 타이틀인데, 나중에 같이 확인하면서 수정하면 될 것 같습니다!

2024-05-31 01:56 UTC, dmstjdhdh commented on src/Navigation.tsx
> +                title: '핀 찍기',
핀이 맞는 것 같습니다. '핑'으로 표시된 단어들은 다 핀으로 바꿀게욥

2024-05-31 02:05 UTC, dmstjdhdh commented on src/pages/ReprocessedIssueDetailPage.tsx
> +  const setBookMarkState = useSetRecoilState<bookMarkInfo>(bookMarkState);
다 바꿨습니다! 감사해요 :)

2024-05-31 02:05 UTC, dmstjdhdh commented on src/Navigation.tsx
> +              options={({
넵 페이지 헤더도 코드 길이가 길기도하고, 커스텀해서 사용 가능한 헤더를 네비게이션에 적용하는 방식이 더 좋은 것 같아, 이렇게 작성하였습니다. 버그 해결도 동시에 하고요.

2024-05-31 02:07 UTC, dmstjdhdh commented on src/Navigation.tsx
> +              options={({
백버튼이 잘 작동하지 않는 이유가, 커스텀 헤더를 직접 페이지에 배치하였기 때문으로 파악했기 때문에, 커스텀 헤더를 네비게이션에 적용하는 방식으로 변경했습니다.

2024-05-31 02:09 UTC, dmstjdhdh commented on src/Navigation.tsx
> +                        key="check"
헤더의 왼쪽이나 오른쪽에 svg아이콘을 넣으려면, leftElement,나 rightElement에 JSX컴포넌트를 배열의 형태로 전달하게 되는데, 이 때문에 key값을 각각 컴포넌트에 전달해줘야합니다. 따라서 아이콘이 하는 기능과 관련된 문자를 key값에 저장하였습니다!

2024-05-31 02:09 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionPostCheckButton.tsx
> +  const opinionPost = useRecoilValue(opinionPostState);
넵넵 useRecoilValue는, 상태의 값을 읽어오는 용도로 사용 가능합니다!

2024-05-31 02:10 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionPostCheckButton.tsx
> +    if (activity == 'OpinionPost' && !isLoading) {
체크 버튼은, 의견 쓰기 페이지와 의견 핀 찍기 페이지 둘 다 사용하게 되는데, 전자는 의견 쓰기 페이지, 후자는 의견 핀 찍기 페이지에서의 버튼 클릭 동작을 정의한 것입니다!

2024-05-31 02:10 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionPostCheckButton.tsx
> +    if (activity == 'OpinionPin') {
넵 핀 찍기 페이지에서는 따로 Api요청을 하는 과정이 없기 때문에, 필요 없는 상태입니다!

2024-05-31 02:12 UTC, dmstjdhdh commented on src/recoil/opinionPostState.ts
> +    opinionId: 0,
이슈 id나 opinionid는 모두 1로 시작하기도 하고, 이 둘은 타입이 number로 지정되어있는데, 각각 (number|null)로 지정해준다면 더 헷갈릴 것 같아서, 이렇게 작성했습니다.

2024-05-31 03:42 UTC, Cyma-s approved these changes
수고하셨습니다!

2024-05-31 06:37 UTC, merged