Feat/#7 가짜뉴스 UI 제작 및 연동
Neupinion/Neupinion-App pull request #12
Opened 2024-02-04 15:47 UTC by dmstjdhdh

## 💬리뷰 참고사항

- /src/asset/icon에 svg 아이콘 추가
- /src/dummy는 백엔드 연동과 동시에 삭제될 파일

### features

- FakeIssueIcon.tsx는, 조회수와 포스트잇 갯수를 Props로 받아 슬라이드를 업데이트시켜주는 컴포넌트입니다.
- FakeIssueItem.tsx은, 가짜뉴스 슬라이드 내에서 보여지는 카드 아이템 UI입니다. 애니메이션 수치가 여기에 있습니다.
- FakeIssueSlider.tsx는, FakeIssueItem들을 슬라이드할 수 있도록 하는 컴포넌트입니다.
- Indicator.tsx는, data와 slideIndex를 Props로 받아, 구현한 인디케이터입니다.
- cardAnizSize는, FakeIssueItem의 애니메이션을 다루기 위한 상수가 있습니다. (애니메이션 관련해서는 설명이 필요할 것 같으니 필요하다면 회의 요청 부탁드리겠습니다.)

### pages

- TestPage.tsx에서, MainPage에서 어떻게 컴포넌트를 가져오고 백엔드와 소통할지에 대해서 알 수 있습니다.

### shared

- GlobalTextStyles.ts를 통해, MainPage에 들어갈 Title의 Style을 통일할 수 있습니다.
- theme.ts에서, Linear Gradient 재사용을 위한 Gradient 타입이 추가되었습니다.
- news.ts에서는, 재가공 이슈, 후속 이슈 등이 가질 수 있는 데이터의 타입등을 정의할 수 있을 것 같습니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

(close) #7

2024-02-06 06:47 UTC, Cyma-s reviewed
해내셨군요. 축하드립니다

2024-02-11 15:05 UTC, hayeounglee requested changes
cardImage에 리뷰 남겼습니다. 확인 부탁드릴게요.

2024-02-11 15:05 UTC, hayeounglee commented on src/features/remakeissue/components/FakeIssueItem.tsx
> +    borderTopRightRadius: 10,
resize  같은 Props 를 사용해보는 건 어떨까요? ex) resizeMode="cover"
resize는 다음과 같은 기능이 있습니다.
1. 가로 세로 비율을 유지한 상태로 이미지를 리사이징한다.
2. 이미지와 뷰의 가로 세로 비율이 일치하지 않을 경우 이미지의 일부분이 잘린다.

2024-02-12 06:40 UTC, hayeounglee approved these changes

2024-02-13 05:05 UTC, merged