Feat/#128 의견 쓰기 페이지에서, 필수 요소가 입력되지 않았을 때의 토스트를 제작한다
Neupinion/Neupinion-App pull request #130
Opened 2024-06-07 06:52 UTC by dmstjdhdh

## 💬리뷰 참고사항
- ToastProvider를 이용해서, 의견 쓰기 과정에서 필요 요소들이 모두 작성되지 않았다면 경고 Toast를 띄우도록 개발하였습니다.

https://github.com/Neupinion/Neupinion-App/assets/71542970/bd0e4300-b49b-4f3e-9011-4f8df7f80afa

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #128

2024-06-07 11:17 UTC, Cyma-s requested changes
필요한 부분인데 시간이 없어서 못 만들었던 부분이네요
단순 코드 수정 리뷰 추가했습니다!

2024-06-07 11:17 UTC, Cyma-s commented on src/shared/components/toast/Toast.tsx
> +  onHide: () => void;
이렇게 네이밍 하는 게 일반적인가요??

2024-06-07 11:17 UTC, Cyma-s commented on src/shared/components/toast/ToastContext.tsx
> +  );
```suggestion
  const showToast = useCallback(
    (msg: string) => {
      if (!isAnimating) {
        setMessage(msg);
      }
    }, [isAnimating]);
```

2024-06-10 05:24 UTC, dmstjdhdh commented on src/shared/components/toast/Toast.tsx
> +  onHide: () => void;
onFocus, onPress와 같이, Toast가 숨겨졌을 때의 동작을 onHide로 했습니다. Toast는 열고 닫는 개념이 아닌 것 같아서, 지금까지 onClose와 같은 네이밍을 팝업에서 썼는데, 이것오 onClose 같은 네이밍이 더 적절할까요?

2024-06-11 09:47 UTC, merged