Feat/#21 메인페이지 컴포넌트 제작 및 데이터 타입 정의
Neupinion/Neupinion-App pull request #22
Opened 2024-02-14 07:37 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 재가공이슈, 후속이슈 타입을 변경하였습니다.
- 데이터를 받아와서, Props로 전달하는 MainPage.tsx를 작성하였습니다.
- 개발한 컴포넌트를 쉽게 붙일 수 있도록, 개발하였습니다.
- svg 아이콘을 import하여 사용할 수 있도록, 모듈 설치를 한 후, custom.d.ts 파일을 작성하였습니다.

https://github.com/Neupinion/Neupinion-App/assets/71542970/41e17fce-b8d9-4ebf-9b78-1e5556c6011b

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #21

2024-02-14 12:28 UTC, hayeounglee requested changes
리뷰 계속 남기고 있습니다. 다 완료되면 또 알려드릴게요!

2024-02-14 12:28 UTC, hayeounglee commented on src/pages/MainPage.tsx
> +    height: 30,
width는 Dimensions를 사용하고,
height는 사용하지 않은 이유는 무엇인가요?

2024-02-14 12:28 UTC, hayeounglee commented on src/pages/MainPage.tsx
> +    alignSelf: 'center',
alignItems가 아니라  alignSelf로 한 이유가 있나요?

2024-02-14 15:14 UTC, hayeounglee requested changes

2024-02-14 15:14 UTC, hayeounglee commented on src/pages/MainPage.tsx
> +            <WithLocalSvg width={20} height={20} asset={MainSearch as ImageSourcePropType} />
svg 파일을 로드할 수 있는 방법이 여러개 있다고 논의 했던 것 같은데
그 중에서 'WithLocalSvg' 컴포넌트를 이용한 이유는 무엇인가요?

2024-02-15 03:11 UTC, dmstjdhdh commented on src/pages/MainPage.tsx
> +    height: 30,
좋은 질문이라고 생각합니다. 

Dimensions.get('window').width는, 자바스크립트에서, 고정된 화면창의 넓이를 가져오게 됩니다. 기기마다 해상도가 달라서 대응하기 위해서 가져온 방식입니다.

Dimensions.get('window)'.height같은 경우에는, 기기의 화면 높이를 가져오는데, 저희 어플리케이션에서는 위아래로 내리는 스크롤뷰형식을 가지고 있기 때문에, 사용할 기회가 없을 것 같다는 생각이 듭니다!

2024-02-15 03:20 UTC, dmstjdhdh commented on src/pages/MainPage.tsx
> +    alignSelf: 'center',
이 버튼 자체를 center로 정렬시키기위해서 alignItems를 사용했습니다. headerArrow의 스타일이 적용된 버튼을 center로 정렬하기 위한 방법은 두 가지로 생각이 드는데,

headerArrow가 들어있는 headerLeftContainer에 alignItmes center속성을 넣는것, 그리고 위 코드와 같이 해당 버튼 자체에 alignSelf center를 넣는것입니다. 어떤방식을 사용해도 괜찮지 않을까? 라는 생각에 이렇게 사용한 것 같아요!

2024-02-15 03:20 UTC, dmstjdhdh commented on src/pages/MainPage.tsx
> +            <WithLocalSvg width={20} height={20} asset={MainSearch as ImageSourcePropType} />
저희는 디자이너분들이 계셔서, svg아이콘 자체를 asset/icon에 저장하고 사용할 수 있는 환경인 것 같아요. 그래서, 파일을 불러와서 쉽게 보여주는 방식인 WithLocalSvg를 선택하게 된 것 같습니다! 만약 더 좋은 방식이 있다면 이후에 리팩토링해도 괜찮을 것 같아요.

2024-02-15 03:43 UTC, hayeounglee requested changes

2024-02-15 03:54 UTC, hayeounglee commented on src/pages/MainPage.tsx
> +    alignSelf: 'center',
그렇군요 이해했습니다!

2024-02-15 04:23 UTC, dmstjdhdh commented on src/pages/MainPage.tsx
> +            <WithLocalSvg width={12} height={12} asset={MainArrowSvg as ImageSourcePropType} />
WithLocalSvg의 asset 속성은, ImageSourcePropType의 타입을 가지는 props만 전달받습니다. 

하지만, MainArrowSvg는, custom.d.ts파일을 확인해보시면, svg파일들의 타입이 안정적으로 사용되기 위해서 React.FC<SvgProps>와 같은 타입으로 export되고있는것을 확인하실 수 있습니다.

여기서 MainArrowSvg as ImageSourcePropType는, 이 MainArrowSvg를 이미지 형태의 타입으로 재정의하여 asset에 할당해야지 오류가 나지 않고, 정상적으로 적용되더라고요! 따라서 이런 방식으로 코드를 작성하였습니다.

2024-02-15 04:52 UTC, hayeounglee commented on src/pages/MainPage.tsx
> +            <WithLocalSvg width={12} height={12} asset={MainArrowSvg as ImageSourcePropType} />
설명 감사합니다. 다음에 아이콘 넣을 떄 참고하겠습니다!

2024-02-15 05:33 UTC, hayeounglee approved these changes

2024-02-16 06:02 UTC, merged