Feat/#37 달력 모달의 기능을 추가, 달력 컴포넌트의 테스트 코드를 작성
Neupinion/Neupinion-App pull request #40
Opened 2024-02-27 11:23 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 달력 컴포넌트를 요구사항에 맞추어 수정하였습니다. (Expo 앱 확인)
- 달력 모달의 테스트 코드를 작성했습니다.
- 가짜뉴스 기능 단위의 테스트 코드를 작성했습니다.
- 후속이슈 기능 단위의 테스트 코드를 작성했습니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #37 #38

2024-02-28 06:17 UTC, dmstjdhdh commented
달력 버그 고치기

2024-02-28 15:42 UTC, hayeounglee requested changes
리뷰 부탁합니다!

2024-02-28 15:42 UTC, hayeounglee commented on src/features/date/components/DateModal.test.tsx
> +    expect(screen.getByText('날짜 선택')).toBeTruthy();
날짜 선택이라는 단어가 화면에 나타나는지로 모달이 열렸는지 테스트할 수 있군요!

2024-02-28 15:42 UTC, hayeounglee commented on src/features/remakeissue/components/FakeIssue.test.tsx
> +    expect(screen.getByTestId('EmptyData')).toBeTruthy();
View 태그에 id를 설정함으로써 테스트할 수 있군요! 
저도 다음에 적용해봐야겠어요!

2024-02-28 15:42 UTC, hayeounglee commented on src/features/remakeissue/components/FakeIssue.test.tsx
> +    const allElementsIndicator = screen.queryAllByTestId(/indicator_/);
`/indicator_/ `코드는 어떤 id를 가진 데이터를 불러오나요?

2024-02-28 15:42 UTC, hayeounglee commented on src/features/date/components/DateModal.tsx
> +      Animated.parallel([
Animated.parallel은 여러 애니메이션을 병렬로 실행할 때 사용하나요?
추가한 에니메이션은 어떤 기능을 하는지도 궁금합니다!

2024-02-29 05:43 UTC, dmstjdhdh commented on src/features/date/components/DateModal.test.tsx
> +    fireEvent.press(screen.getByTestId('undefined.day_' + cvtParamDate(new Date())));
UI 컴포넌트와 상호작용하는 이벤트를 시뮬레이션하는데에 사용합니다. 버튼 클릭이나, 텍스트가 변경되는걸 추적할 수 있습니다!

2024-02-29 05:43 UTC, dmstjdhdh commented on src/features/date/components/DateModal.tsx
> +          testID={'dim-button'}
넵 맞습니다! 감사합니다 😊

2024-02-29 05:44 UTC, dmstjdhdh commented on src/features/date/components/DateModal.test.tsx
> +    expect(screen.getByText('날짜 선택')).toBeTruthy();
넵, 모달 내에 들어있는 UI가 있는지 없는지로 모달이 열려있는지 확인이 가능할 것 같아서 이렇게 해봤습니다!

2024-02-29 05:45 UTC, dmstjdhdh commented on src/features/remakeissue/components/FakeIssue.test.tsx
> +    expect(screen.getByTestId('EmptyData')).toBeTruthy();
넵. testID라는 속성이 있더라고요. 이름을 설정하고, 찾아서 테스트하는 방식 좋은 것 같습니다!

2024-02-29 05:46 UTC, dmstjdhdh commented on src/features/remakeissue/components/FakeIssue.test.tsx
> +    const allElementsIndicator = screen.queryAllByTestId(/indicator_/);
현재 기능에서, 인디케이터들은, indicator_(번호)의 형식의 testID를 가지고 있습니다. 그래서, screen.queryAllByTestId(/indicator_/);는 렌더링한 스크린에서 indicator_라는 글자가 포함된 id들의 ui를 모두 가져오게 됩니다!

2024-02-29 09:03 UTC, dmstjdhdh commented on src/features/date/components/DateModal.tsx
> +          testID={'dim-button'}
지금, 달력 관련된 오류를 다시 수정하여 expo go에 업데이트 했습니다. 다시 확인해주실 수 있을까요?

2024-02-29 09:04 UTC, dmstjdhdh commented on src/features/date/components/DateModal.tsx
> +      Animated.parallel([
Animated.parallel은 여러개의 애니메이션을 동시에 시행할 수 있도록 해주는 방법입니다! 그리고 추가한 애니메이션은 3가지의 기능을 합니다. y좌표의 이동, 달력 스케일 변경, 달력의 투명도 변경 입니다.

2024-03-01 01:48 UTC, hayeounglee commented on src/features/date/components/DateModal.tsx
> +          testID={'dim-button'}
수정된거 확인했습니다!!

2024-03-02 09:44 UTC, hayeounglee approved these changes

2024-03-02 14:42 UTC, merged