Config/#18 프로젝트에 폰트를 적용할 수 있도록 한다.
Neupinion/Neupinion-App pull request #45
Opened 2024-03-01 05:01 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 폰트는 비동기적으로 불러오는 방식입니다.
- 로딩이 다 되면 앱이 불러와지도록 개발하였습니다.
- fontFamily.pretendard.원하는스타일 의 방식으로 적용이 가능합니다.
- 이후, 폰트를 적용해야하는 컨텐츠는 리팩토링을 해야합니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #18

2024-03-02 10:27 UTC, hayeounglee requested changes
리뷰 부탁해요~

2024-03-02 10:27 UTC, hayeounglee commented on App.tsx
> +  const isLoaded = useCachedResources();
useCachedResources()함수는 폰트를 여러번 불러오는 것을 막기 위한 장치라고 보면 되나요?

2024-03-02 10:27 UTC, hayeounglee commented on src/useCachedResources.ts
> +  useEffect(() => {
expo-google-fonts 패키지 같은 곳에서 특정 폰트를 가져오는 상황일 때 
작성한 코드와 같이 앱이 시작되기 전에 로드가 되었는지 확인하는 작업을 한다는 글을 본적이 있습니다.
지금 상황도 같은 상황이라고 볼 수 있는 건가요?

2024-03-02 14:41 UTC, dmstjdhdh commented on src/useCachedResources.ts
> +  useEffect(() => {
넵 맞습니다. 앱에서 폰트가 로드가 되어있지 않다면, 정상적으로 UI를 불러오지 않게 하였습니다. isLoadingComplete가 false라면, null을 반환하도록 했습니다. 이후에는, ~~를 로딩중이에요! 같은 화면이 디자인되면 어떨까 하는 생각도 있습니다.

2024-03-03 17:17 UTC, hayeounglee approved these changes

2024-03-04 14:41 UTC, merged