Feat/#44 재가공 이슈 상세페이지 UI 제작
Neupinion/Neupinion-App pull request #46
Opened 2024-03-01 16:09 UTC by hayeounglee

## 💬리뷰 참고사항
- API 연동 및 신뢰도 평가하기 UI를 제외한 나머지 UI 제작 완료했습니다.
- 컨텐츠, 의견 쓰기,동일 카테고리 최신 소식 UI 를 제작했습니다.
- '의견쓰기' 부분의 svg 파일은 수정할 부분이 있으면 추출하는 방법에 대해 더 알고 나서 수정할 예정입니다.

## #️⃣연관된 이슈

closes #44

2024-03-04 14:40 UTC, dmstjdhdh requested changes
코드 리뷰 부탁드립니다!

2024-03-04 14:40 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +interface ReProcessedIssueProps {
첫 코드리뷰때 말씀드렸던 부분입니다! 해당 컴포넌트에서 사용하는 Props에 대해서 interface를 선언한 것이기 때문에, CategoryLatestNewsSliderProps가 어떨까요? (겁나 기네요)

2024-03-04 14:40 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +  };
페이지 이동 관련하여서, Navigation을 구현하였는데, 제 의견쓰기 활동 PR을 코드리뷰 해주시면, 여기에도 적용할 수 있을 것 같습니다. 리뷰 잘 부탁드리겠습니다!

2024-03-04 14:40 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +        snapToInterval={Dimensions.get('window').width}
해당 코드는 의도가 조금 불분명해보여요. snapToInterval={Dimensions.get('window').width} 코드를 사용하는 의도에 대해서 생각해보시면, 필요한 코드인지 아닌지 아마 감이 오실 것 같습니다!

2024-03-04 14:40 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNewsSliderItem.tsx
> +const ReProcessedIssueItem = ({ item }: ReProcessedIssueProps) => {
컴포넌트 이름이 잘못된 것 같아요. CategoryLatestNewsSliderItem.tsx 파일이니... 이에 맞춰서 CategoryLatestNewsSliderItem으로 선언되어야할 것 같습니다.

2024-03-06 03:07 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +        snapToInterval={Dimensions.get('window').width}
snapToInterval은 스크롤 뷰가 snapToInterval 값의 배수에서 멈추도록 하는 기능이였는데 여기서는 필요없을 것 같네요,
삭제했습니다!

2024-03-06 03:21 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +      <FlatList
넵 알겠습니다, FlatList 자체에 스타일을 주겠습니다. (marginBottom: 50)
최대 5개의 컨텐츠인지는 화면설계서에 나와있지 않아 질문한다음 최종반영하겠습니다.

2024-03-06 03:27 UTC, hayeounglee commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +const OpinionWriteSlider = () => {
질문 답변 전에, 제가 디자인 부분에서 헷갈리는게 있어 먼저 확인하면 좋을 것 같은 부분이 있는데요,
의견쓰기 부분에서,
만약 사용자가 의견을 많이 쓴 경우 슬라이드 형식으로 보이는건가요? 아니면 아래 사진처럼 2개반 보이는 건가요?
<img width="440" alt="image" src="https://github.com/Neupinion/Neupinion-App/assets/95111439/917d063b-46c2-4e0c-ad85-6c4662705ac2">

2024-03-06 03:31 UTC, hayeounglee commented on src/features/remakeissue/components/ReliabilitySlider.tsx
> +          <WithLocalSvg height={66.94156} asset={Moon3Svg as ImageSourcePropType} />
혹시 왜 상수로 가져오면 좋을까요?
이게 깔끔하지 않은(?) svg 높이 값이여서 그런가요?

2024-03-06 04:13 UTC, dmstjdhdh commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +const OpinionWriteSlider = () => {
생각해보니, 이전에 의견쓰기가 슬라이더 형태로 제공된다고 했던 것 같아요. 하지만 이거는 디자인팀에 여쭤봐서 확실하게 해야할 것 같아요!

2024-03-06 04:15 UTC, dmstjdhdh commented on src/features/remakeissue/components/ReliabilitySlider.tsx
> +          <WithLocalSvg height={66.94156} asset={Moon3Svg as ImageSourcePropType} />
제 생각에는 두 개의 장점이 있습니다. 깔끔하지 않은 것 때문은 아닙니다!

1. 어떤 기능에서 적용되는 숫자인지 코드 읽기가 좋아진다. (상수 이름에서 유추 가능)
2. 수정할 때, 상수에 있는 숫자만 수정하면 된다. (각각 66.94156이 있는 부분을 다 바꾸지 않아도 됨)

2024-03-06 07:42 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +      <FlatList
UI가 이상하게 떠다니는건 어떤 경우일까요.. 나중에 회의 떄 알려주셔도 좋을것 같아요!

2024-03-06 07:45 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +      <FlatList
ScrolllView + map을 사용하는 상황과 비교했을 떄 FlatLIst를 사용한 이유가 궁금하신건가요?
랜더링 할 때, 화면에 보이는 것만들만 가져오고 스크롤을 내려랴 볼 수 있는 아이템들을 가져오지 않아 효율적인 랜더링이 가능하다고 생각하여 사용했습니다.

그러나 방금 생각해보니 지금 이 상황은 그런 상황이라고 하기가 애해하다고 볼 수 있을것 같네요,
스크롤 뷰 안에 스크롤 뷰 안에 넣는 상황인지라..

map만 사용하는 걸로 바꿀까요?

2024-03-06 08:06 UTC, hayeounglee commented on src/features/remakeissue/components/ReliabilitySlider.tsx
> +        <TouchableOpacity
변경에 용이하게 바꾸는게 좋을 것 같습니다. 감사합니다!

2024-03-06 15:00 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNewsSlider.tsx
> +      <FlatList
넵, 저는 FlatList는, 리스트를 나열해야할때가 아닌, (리스트를 나열 + 스크롤) 이 두가지가 모두 필요하면 사용하는 편이에요. 왜냐면 나열하는건 그냥 map을 써서, 컴포넌트를 나열하면 되니까요. 사용 의도랑 맞지 않아서 제안 드립니다!

그리고 UI가 떠다니는 현상도, FlatList 컴포넌트가 워낙 스크롤이 가능하게 만드는 기능이라서 생기는 것 같더라고요. 회의때 보여드리겠습니다...ㅋㅋㅋ

2024-03-07 04:19 UTC, dmstjdhdh approved these changes
리뷰 끝났습니다!

2024-03-18 12:59 UTC, closed without merging