Feat/#43 상세페이지-> 의견쓰기 -> 핀 찍기의 기능을 개발한다.
Neupinion/Neupinion-App pull request #49
Opened 2024-03-02 14:36 UTC by dmstjdhdh

## 💬리뷰 참고사항

-페이지 간의 네비게이션이 구현되어 있습니다.
- Opinion$$$형태의 파일이 추가되었습니다.

## #️⃣연관된 이슈

closes #43

2024-03-06 12:43 UTC, hayeounglee requested changes
리뷰 부탁드려요!

2024-03-06 12:43 UTC, hayeounglee commented on src/Navigation.tsx
> +        <Stack.Group>
Group으로 묶은 이유는 무엇인가요?

2024-03-06 13:36 UTC, hayeounglee requested changes
리뷰 부탁드립니다

2024-03-06 13:36 UTC, hayeounglee commented on src/pages/OpinionPinPage.tsx
> +        <Text style={styles.topTextStyle}></Text>
두 svg 사이를 벌리기 위해 저는 space-between을 사용했는데
이롷게 topTextStyle을 넣는 것도 좋은 것 같네요!

2024-03-06 13:36 UTC, hayeounglee commented on src/pages/OpinionPinPage.tsx
> +                <TouchableOpacity style={styles.pin} onPress={onClickCheckButton}>
오른쪽 상단에 있는 보라색 체크버튼 뿐만 아니라
핀버튼을 눌렀을 때도 같은 기능이 적용되는데(onClickCheckButton)
이게 화면설계서에는 없는 기능이지 않나요?

2024-03-06 13:36 UTC, hayeounglee commented on src/pages/OpinionPinPage.tsx
> +                <TouchableOpacity style={styles.pin} onPress={onClickCheckButton}>
이런 기능이 있을 경우
첫번째 인덱스에 해당되는 문단에 핀을 꽂은 상태에서
다른 인덱스에 해당되는 문단의 핀을 클릭할 경우 페이지가 이동되는 것 같습니다.

2024-03-06 13:36 UTC, hayeounglee commented on src/pages/OpinionPostPage.tsx
> +            {sentenceIndex !== undefined && (
sentenceIndex은 무엇인가요? RouteProp과 연관되어 있나요?

2024-03-06 13:36 UTC, hayeounglee commented on src/features/opinionpost/components/OpinionWriteContainer.tsx
> +    <View style={styles.textContainer}>
화면설계서에 300자에 맞게 박스 크기가 자동으로 변경된다는데
이게 구현이 안된 것 같아요 확인부탁드립니다!

2024-03-06 13:36 UTC, hayeounglee commented on src/features/opinionpost/components/SentenceBox.tsx
> +  sentenceText: {
![image](https://github.com/Neupinion/Neupinion-App/assets/95111439/8d57a63b-b2ed-4b5c-8b69-a6438dbd6551)
문단이 꺠지는 것 같아요,
왜 이렇게 나오는지 모르겠는데 저도 고민해 볼게요.

2024-03-07 14:27 UTC, hayeounglee commented on src/features/opinionpost/components/SentenceBox.tsx
> +  sentenceText: {
앗 용우님 핸드폰에는 이런 오류가 안나온다는 말씀이신가요?!

2024-03-07 14:28 UTC, hayeounglee commented on src/Navigation.tsx
> +        <Stack.Group>
과심사를 분리한다는 내용을 좀 더 자세히 설몀해 주실 수 있을까요?

2024-03-07 14:40 UTC, hayeounglee commented on src/pages/OpinionPostPage.tsx
> +            {sentenceIndex !== undefined && (
고급 기능이네요.. 설명 감사합니다 :)

2024-03-12 03:27 UTC, dmstjdhdh commented on src/Navigation.tsx
> +        <Stack.Group>
넵 맞습니다!

2024-03-12 03:28 UTC, dmstjdhdh commented on src/features/opinionpost/components/OpinionWriteContainer.tsx
> +    <View style={styles.textContainer}>
협의를 하였을 때, 텍스트 박스의 크기는 고정인 상태로 스크롤 가능하도록 개발하였습니다!

2024-03-15 07:10 UTC, closed without merging