Feat/#50 의견포스트잇 확대 팝업 제작
Neupinion/Neupinion-App pull request #51
Opened 2024-03-05 15:37 UTC by dmstjdhdh

## 💬리뷰 참고사항

![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/ca0fe591-5b75-4a15-ae3d-f8be67d3e7c6)

- 화면 전체에 등장하는 Popup을 제작하였습니다.
- TestPage.tsx에서, Modal에 props를 전달하는 방식이나, 어떤 방식으로 적용해야할지 적혀있습니다.
- OpinionPostItPopup.tsx에서, 각각 버튼을 눌렀을 떄, 어떤 동작이 필요한지 적혀있습니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #50

2024-03-06 14:39 UTC, hayeounglee requested changes
답변 부턱드립니다!

2024-03-06 14:39 UTC, hayeounglee commented on src/features/opinionpost/popup/OpinionPostItPopup.tsx
> +    height: 480,
흠 제 핸드폰은 이렇게 아래 버튼 두개가 container 밖에 위치하게 나옵니다.
나중에 의견 쓰기 글자수를 고려해서
container 높이가 유동적으로 변학게 할 것 같은데 어떻게 생각하시는지 궁금합니다!

2024-03-07 04:14 UTC, dmstjdhdh commented on src/features/opinionpost/popup/OpinionPostItPopup.tsx
> +    height: 480,
넵! 컨테이너 스타일을 유동적으로 반영할 수 있도록 수정하였습니다! 좋은 의견 감사합니다!

2024-03-07 14:54 UTC, hayeounglee approved these changes

2024-03-15 07:10 UTC, closed without merging