Feat/#53 앱 공유 기능을 개발한다.
Neupinion/Neupinion-App pull request #54
Opened 2024-03-06 04:53 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 지정된 링크를 휴대폰에 있는 공유 가능한 플랫폼에 공유할 수 있도록 하는 기능을 추가하였습니다.
- 임시로, 아이폰은 appstore 카카오톡, 갤럭시는 playstore 카카오톡 앱 링크를 공유하도록 하였습니다.
- Expo Go에서도 확인 가능합니다.
   - "test: 웹 링크 공유 시도" -> 웹 링크를 공유하는 기능
   - "feat: 카카오톡의 앱...있는 컴포넌트 제작" -> 앱 링크를 공유하는 기능

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #53

2024-03-06 15:17 UTC, hayeounglee requested changes
리뷰 부탁드립니다!

2024-03-06 15:17 UTC, hayeounglee commented on src/pages/AppLinkTestPage.tsx
> +    Platform.OS === 'ios'
앱 링크가 원래 os마다 다른가요?

2024-03-06 15:17 UTC, hayeounglee commented on src/pages/AppLinkTestPage.tsx
> +      alert(e);
e 대신 에러 메세지를 작성 해주는 건 어떨까요?

2024-03-07 04:14 UTC, dmstjdhdh commented on src/pages/AppLinkTestPage.tsx
> +    Platform.OS === 'ios'
넵...! ios에서는, 앱스토어, android에서는, 플레이스토어로 연결될 수 있도록 해야합니다!

2024-03-07 04:15 UTC, dmstjdhdh commented on src/pages/AppLinkTestPage.tsx
> +      alert(e);
e.message를 작성하도록 수정해보겠습니다!

2024-03-15 07:10 UTC, dmstjdhdh commented
- [ ]

2024-03-15 07:10 UTC, closed without merging