Feat/#43-2 상세페이지-> 의견쓰기 -> 핀 찍기의 기능을 개발한다.
Neupinion/Neupinion-App pull request #58
Opened 2024-03-13 05:31 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 페이지 간의 네비게이션이 구현되어 있습니다.
- Opinion$$$형태의 파일이 추가되었습니다.
- 현재 기획문의 3가지가 슬랙에 나와있는 상태이며, 답변을 기다리고 있습니다.
- Expo Go에서 "fix: 컴포넌트 부모…" 확인 부탁드립니다.

## #️⃣연관된 이슈

closes #43 #48

2024-03-13 11:22 UTC, hayeounglee requested changes
리뷰 부탁합니다!

2024-03-13 11:22 UTC, hayeounglee commented on src/Navigation.tsx
> +      <Stack.Navigator
나중에 초기 라우트를 'MainPage'로 설정함으로써 앱이 실행될 때 처음으로 표시되는 화면이 'MainPage'가 되도록 하면 되나요?
 <Stack.Navigator initialRouteName="MainPage">

2024-03-13 11:22 UTC, hayeounglee commented on src/pages/OpinionPostPage.tsx
> +import { StackNavigationProp } from '@react-navigation/stack';
이 StackNavigationProp stack인가요?
리액트 네이티브는 stack 형식으로 현재 view 에서 위로 쌓이는 형식으로 페이지를 이동한다고 보면 되나요?

2024-03-13 11:22 UTC, hayeounglee commented on src/pages/OpinionPostPage.tsx
> +  const navigation = useNavigation<StackNavigationProp<RootStackParamList>>();
navigation을 props로 전달하지 않고
이렇게 선언한 이유가 무엇인가요?

2024-03-13 11:22 UTC, hayeounglee commented on src/pages/OpinionPinPage.tsx
> +        <Text style={styles.topTextStyle}></Text>
두 svg 사이를 벌리기 위해 저는 space-between을 사용했는데
이롷게 topTextStyle을 넣는 것도 좋은 것 같네요!

2024-03-13 11:22 UTC, hayeounglee commented on src/pages/OpinionPostPage.tsx
> +            {sentenceIndex !== undefined && (
sentenceIndex은 무엇인가요? RouteProp과 연관되어 있나요?

2024-03-13 11:22 UTC, hayeounglee commented on src/features/opinionpost/components/SentenceBox.tsx
> +  sentenceText: {
![image](https://github.com/Neupinion/Neupinion-App/assets/95111439/443fddf9-8aaa-4750-9543-8b6015569fc5)
문단이 꺠지는 것 같아요,
왜 이렇게 나오는지 모르겠는데 저도 고민해 볼게요.

2024-03-14 03:22 UTC, dmstjdhdh commented on src/Navigation.tsx
> +      <Stack.Navigator
넵! 저희 상세페이지 스프린트 마무리할때, 메인페이지로 하면 될 것 같아요!

2024-03-14 03:22 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +import { StackNavigationProp } from '@react-navigation/stack';
넵 맞습니다! 리액트 네이티브는 스택 형식으로 네비게이션이 이루어지고, back을 할때마다 last in 페이지가 pop되는 것 같습니다.

2024-03-14 03:22 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +  const navigation = useNavigation<StackNavigationProp<RootStackParamList>>();
navigation을 각각의 컴포넌트에 props로 전달하면, 이전에 개발한 기능, 그리고 앞으로 있을 페이지에도 모두 props로 전달해야하기 때문에, 좋지 않을 것 같았습니다.

정말 필요한 props만 컴포넌트에서 정의되어있으면 좋겠다는 의도.
모든 페이지에서 필요한 props라면, 다른 방식으로 props를 공유하는게 좋겠다는 생각이 들었습니다.
useNavigation은 다음과 같은 방법으로 개발하기 좋은 방식이라고 생각이 들었습니다!

2024-03-14 03:25 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +            {sentenceIndex !== undefined && (
sentenceIndex는, 문장 선택 페이지에서, 선택된 문장의 번호를 의미합니다. 선택 되어있지 않는 초기상태에서는, sentenceInde가 undefined로 정의되어있습니다. 만약 선택이 된다면, 예시 문장들에서는 1~4 사이에 숫자를 가지게 됩니다.

pinPage로 이동하고 돌아올 때, 그리고 다른 페이지에서 이 페이지로 이동할때
```javascript
const sentenceIndex = route.params?.sentenceNumber;
```

이런식으로 해당 문장의 번호를 받아오게됩니다.

2024-03-14 03:25 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +            {sentenceIndex !== undefined && (
만약 페이지 이동할때, sentenceIndex를 전달 안하면, undefined로 되고,

```javascript
navigation.navigate('OpinionPost', { sentenceNumber: selectedPinIndex });
```

이런식으로 이동할때, props의 형태로 전달하면, 해당 형태에 맞춰서 전달하게 됩니다.

2024-03-14 03:27 UTC, dmstjdhdh commented on src/features/opinionpost/components/SentenceBox.tsx
> +  sentenceText: {
이렇다할 원인들을 저도 파악하지 못하고 있습니다...! 제 핸드폰 ios, android 모두 이상 없이 나오고 있는데, 다른 버전으로 다시 올렸을 때, 괜찮으면 넘어가는건 어떨까 싶습니다!

2024-03-14 03:51 UTC, hayeounglee approved these changes

2024-03-15 07:10 UTC, merged