Feat/#62 상세페이지 api 구현
Neupinion/Neupinion-App pull request #67
Opened 2024-03-24 14:36 UTC by hayeounglee

## 💬리뷰 참고사항

- DetailPage의 api를 구현했습니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성
closes #62

2024-03-25 07:33 UTC, dmstjdhdh reviewed
리뷰 답변 부탁드립니다!

2024-03-25 07:33 UTC, dmstjdhdh commented on src/shared/types/news.ts
> +export interface sameCategoryReprocessedIssues{
혹시 sameCategoryReprocessedIssues의 타입의 첫 same이 대문자가 아닌 이유랑, Issues이면 이슈가 복수형인 것 같은데 복수형을 쓴 이유를 알려주실 수 있나요?

2024-03-25 07:33 UTC, dmstjdhdh commented on src/pages/DetailPage.tsx
> +  const getReprocessedIssueList = async () => {
api를 통해 데이터를 다음과 같이 불러오는 방식은 좋은 것 같습니다. 그런데, 저희 개발서버의 url이 그대로 노출되어 github에 공유되는 방식을 피하기 위해서, 제가 이전에 shared파일-> remotes 파일-> axios.ts파일에서, 서버의 url를 가린 후, 이에대한 정보인 baseURL을 포함하는 axios인스턴스 client를 개발했었습니다.

이를 통해서, 코드상에 개발서버 url(보안상) 노출을 없애고, 개발서버 url이 변경되었을 때, baseURL만 수정하면 되는 방식을 생각하고 있었습니다.

그리고 컴포넌트에서 api를 통해 데이터를 불러오는 방식을 보여주는 것 보다, remotes 파일에서 데이터를 불러오는 방식을 정의한 후에, import하는 방식이 더 좋은 것 같습니다.

```javascript
export const getReprocessedIssues = async (date: string) => {
  const { data } = await client.get<ReProcessedIssue[]>('/reprocessed-issue', {
    params: { date: date },
  });

  return data;
};
```

이런식으로 client를 사용하고, 다른 파일에서 get메서드를 정의함으로써 유지보수를 더 고려하는 방식은 어떨까요?

2024-03-25 07:33 UTC, dmstjdhdh commented on src/pages/DetailPage.tsx
> +  const getReprocessedIssueList = async () => {
이 코드는 제가 이전에 작성한 재가공 이슈를 가져오는 코드이며,remakeissue -> remotes폴더를 확인하면 확인하실 수 있습니다.

2024-03-25 07:33 UTC, dmstjdhdh commented on src/features/remakeissue/remotes/sameCategoryReprocessedIssue.ts
> +export const getsameCategoryReprocessedIssues = async (current: string, category: string) => {
이 코드는 어디에서 사용되나요? 다른 곳에서는 안보여서요

2024-03-25 07:33 UTC, dmstjdhdh commented on src/features/remakeissue/components/RemakeIssueContentsSlider.tsx
> +  const getIssueData = async () => {
이렇게 api를 가져오는 방식 또한, DetailPage.tsx에서 제가 리뷰한 방식을 고려해주시면 어떨까 생각합니다!

2024-03-25 07:33 UTC, dmstjdhdh commented on src/features/remakeissue/components/ReliabilityEvaluation.tsx
> +      const response = await axios.put(
http 메서드 중, put 메서드랑 patch 메서드랑 어떤 차이가 있을까요?

2024-03-28 00:39 UTC, hayeounglee commented on src/shared/types/news.ts
> +export interface sameCategoryReprocessedIssues{
수정하는게 맞는 것 같아
대문자로 바꾸고, 단수형으로 바꿨습니다!

2024-03-28 00:57 UTC, hayeounglee commented on src/features/remakeissue/remotes/sameCategoryReprocessedIssue.ts
> +export const getsameCategoryReprocessedIssues = async (current: string, category: string) => {
사용된 곳이 없어 이건 삭제하겠습니다!

2024-03-28 02:14 UTC, hayeounglee commented on src/pages/DetailPage.tsx
> +  const getReprocessedIssueList = async () => {
DetailPage.tsx에서 동일 카테고리소식 부분을
말해주신 것처럼 바꿨는데 확인부탁드립니다!

2024-03-28 02:15 UTC, hayeounglee commented on src/features/remakeissue/remotes/sameCategoryReprocessedIssue.ts
> +export const getsameCategoryReprocessedIssues = async (current: string, category: string) => {
용우님이 리뷰하실때는 사용되지 않은 코드였습니다.
이번에 api 수정하면서 DetailPage에서 사용했습니다!

2024-03-28 02:18 UTC, hayeounglee commented on src/features/remakeissue/components/ReliabilityEvaluation.tsx
> +      const response = await axios.put(
요청을 보내면 PUT은 기존 데이터를 완전히 대체 하고, PATCH는 요청 데이터만 부분적으로 변경한다고 합니다.

이미 아시겠제만.. 저는 이 예시를 보고 확 와닿았습니다!
https://programmer93.tistory.com/39

2024-03-28 10:10 UTC, dmstjdhdh reviewed
api 관련 리뷰 확인 부탁드리겠습니다!

2024-03-28 10:10 UTC, dmstjdhdh commented on src/features/remakeissue/remotes/SameCategoryReprocessedIssue.ts
> +export const getSameCategoryReprocessedIssues = async (current: string, category: string) => {
Swagger에서는, current의 type이 integer로 되어있습니다. 확인 부탁드릴게요!

2024-03-28 10:10 UTC, dmstjdhdh commented on src/features/remakeissue/remotes/RemakeIssueContent.tsx
> +export const getRemakeIssueContent = async (id: string) => {
Swagger에서는 파라미터로 지정된 id의 type이 integer로 되어있습니다!

2024-03-31 15:53 UTC, hayeounglee commented
현재 북마크 api는 오류코드 500이 발생합니다.
이는 swagger에도 동일하게 나오는 오류인데 참고하면 될 것 같습니다!

2024-04-01 06:33 UTC, Cyma-s requested changes
시간되실 때 리뷰 확인해주세요!

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +      });
console log, error 는 언제 필요한가요?

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +  console.log('SameCategory ReprocessedIssues:', reprocessedIssue);
요기도 마찬가지입니다

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +  };
해당 타입과 상수는 다른 파일로 분리되어야 할 것 같아요

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  console.log('myOpinionWrite:', myOpinionWrite);
불필요한 로그 없애주세요

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +              height={99.08478}
해당 값으로 설정된 이유가 있나요?

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +    // top: 5,
주석은 삭제해주세요 😉

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/ReliabilityEvaluation.tsx
> +        `https://dev.neupinion.com/reprocessed-issue/${issueId}/trust-vote`,
현재 dev URL 로 설정되어 있는 이유가 있나요?

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/RemakeIssueContentsSlider.tsx
> +  console.log('RemakeIssueContent:', remakeIssue);
여기서는 fetchData 에서 then, catch 모두 아무것도 하지 않는 것 같은데 이렇게 써야만 하나요? (fetchData 가 이렇게 사용되어야만 하는지...)

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/constants/reliabilty.ts
> +  { id: 1, text: '완전 신뢰', entext: 'HIGHLY_TRUSTED' },
혹시 entext 가 무슨 뜻인가요?

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/components/CategoryLatestNewsItem.tsx
> +}: CategoryLatestNewsSliderItemProps & { category: string }) => {
& operator 를 사용한 이유가 무엇인가요?

2024-04-01 06:33 UTC, Cyma-s commented on src/features/remakeissue/remotes/remakeIssueContent.ts
> +export const getRemakeIssueContent = async (id: number) => {
RemakeIssue <-- 네이밍이 컨벤션과 다른 것 같아요

2024-04-01 06:33 UTC, Cyma-s commented on src/pages/DetailPage.tsx
> +  const id: number = 1;
id 가 1로 고정된 이유는 무엇인가요?

2024-04-01 06:33 UTC, Cyma-s commented on src/pages/DetailPage.tsx
> +      setBookMarkClicked(!bookMarkClicked);
! 연산으로 상태 변경하는 거 좋습니다 👍🏻

2024-04-01 06:33 UTC, Cyma-s commented on src/pages/DetailPage.tsx
>    };
사용되는 곳이 있나요?

2024-04-01 06:33 UTC, Cyma-s commented on src/shared/types/news.ts
> +export interface SameCategoryReProcessedIssue {
`SameCategoryReprocessedIssue` 로 변경바랍니다

2024-04-01 06:33 UTC, Cyma-s commented on src/shared/types/news.ts
> +export interface RemakeIssueContent {
마찬가지로 `ReprocessedIssueContent` 로 변경바랍니다

2024-04-01 06:33 UTC, Cyma-s commented on src/shared/types/news.ts
> +  inReliable: boolean;
오타 있는 것 같습니다 `is` 아닌가욥?

2024-04-01 06:33 UTC, Cyma-s commented on src/shared/types/news.ts
> +interface Content {
이건 export 안 해도 되나요?

2024-04-01 06:33 UTC, Cyma-s commented on App.tsx
> +    // </DateProvider>
PR 올릴 때는 개인적으로 해두었던 주석은 해제하고 올려주세요 :)

2024-04-01 06:46 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +      });
api가 잘 불러와졌는지 확인하고 싶을 때 필요합니다!

2024-04-01 06:49 UTC, Cyma-s commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +      });
log 로 확인하는 건 지양하는 게 좋습니다. 제가 테스트 데이터 많이 채워두겠습니다...ㅋㅋㅋㅋ

2024-04-01 06:53 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +  };
넵 완료했습니다!

2024-04-01 06:59 UTC, hayeounglee commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +              height={99.08478}
피그마에 나와있는 값이 렇게 나와있어서 해당 값으로 설정했습니다.
소수점 아래는 버리고 깔끔하는게 정수로 바꾸는게 좋을 것 같다는 생각이 갑자기 들긴하네요...!

2024-04-01 07:06 UTC, hayeounglee commented on src/pages/DetailPage.tsx
> +  const id: number = 1;
이건 나중에 다른 페이지와 이 상세페이지 사이에 negivation을 구현할 때 바뀌어야 하는 부분입니다.
따라서 최종적으로는 id 는 고정된 값이 아니라 다른페이지에서 어떤 뉴스를 눌렀는지에 따라 바뀌어야 하는 부분인데,
임시로 이렇게 id 값을 설정했습니다!

2024-04-01 07:25 UTC, Cyma-s commented on src/features/remakeissue/constants/reliabilty.ts
> +  { id: 1, text: '완전 신뢰', entext: 'HIGHLY_TRUSTED' },
차라리 value 가 나을 거 같습니다 😂

2024-04-01 07:28 UTC, Cyma-s commented on src/pages/DetailPage.tsx
> +  const id: number = 1;
그렇다면 detail page 가 외부에서 id 를 받아서 바꿔줘야 하지 않나요?

2024-04-01 08:16 UTC, hayeounglee commented on src/pages/DetailPage.tsx
>    };
아직 없는데 
나중에 페이지 네비게이션할 때 최종 구현될 예정입니다

2024-04-01 08:20 UTC, hayeounglee commented on src/shared/types/news.ts
> +export interface SameCategoryReProcessedIssue {
수정완료 했습니다

2024-04-01 08:54 UTC, hayeounglee commented on src/shared/types/news.ts
> +  inReliable: boolean;
발견 감사합니다!

2024-04-01 09:42 UTC, hayeounglee commented on src/features/remakeissue/components/RemakeIssueContentsSlider.tsx
> +  console.log('RemakeIssueContent:', remakeIssue);
fetchData를 useEffect 함수 안에다 쓰는 거에 대한 질문인가요..?

2024-04-01 10:08 UTC, hayeounglee commented on src/features/remakeissue/components/ReliabilityEvaluation.tsx
> +        `https://dev.neupinion.com/reprocessed-issue/${issueId}/trust-vote`,
해당 URL가 보여지지 않게
수정했습니다

2024-04-01 10:15 UTC, hayeounglee commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  console.log('myOpinionWrite:', myOpinionWrite);
내가 작성한 의견쓰기가 []일 때는 아무것도 UI상에 출력이 되지 않아
api가 잘 불러오는지 확신할 수 없어
log 값으로 확인하고 있는 상황입니다..! 
혹시 이런면에서는 필요하지 않을까 싶습니다..!

2024-04-01 11:25 UTC, hayeounglee commented on src/shared/types/news.ts
> +interface Content {
넵 맞습니다!

2024-04-01 11:27 UTC, hayeounglee commented
리뷰 답변 완료했습니다!

2024-04-01 11:38 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +      });
좋습니닷!

2024-04-01 11:38 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +      });
log 들 삭제했습니다!

2024-04-01 11:39 UTC, hayeounglee commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  console.log('myOpinionWrite:', myOpinionWrite);
로그 삭제 했습니닷

2024-04-01 14:21 UTC, dmstjdhdh reviewed
코드리뷰 남겼습니다. 확인 부탁드리겠습니다!

2024-04-01 14:21 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +  }, []);
```javascript
useEffect(() => {
    void fetchData();
  }, []);
```

then, catch문을 사용하지 않는다면 다음과 같이 깔끔하게 정리해도 좋을 것 같습니다!

2024-04-01 14:21 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNewsItem.tsx
> +}: CategoryLatestNewsSliderItemProps & { category: string }) => {
타입을 결합하지 않고, CategoryLatestNewsSliderItemProps에 category를 추가하는건 어떨까요?

2024-04-01 14:21 UTC, dmstjdhdh commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  const [noOpinion, setNoOpinion] = useState(true);
fetchData를 통해서, myOpinionWirte가 비어있다면 noOpinion이 true가 되는 것 같은데, useState를 사용한 이유가 궁금합니다. !myOpinionWrite.length를 확인하거나 하는 방식도 있기 때문입니다

2024-04-01 14:21 UTC, dmstjdhdh commented on src/features/remakeissue/components/ReliabilityEvaluation.tsx
> +  };
이 함수는 remotes에서 관리하지 않는 이유가 있을까요?

2024-04-01 14:21 UTC, dmstjdhdh commented on src/features/remakeissue/components/ReprocessedIssueContentsSlider.tsx
> +  }, []);
위에서 말씀드린 useEffect에서 fetchData를 사용하는 방식에 대해서 여기서도 고민이 필요해봅니다!

2024-04-02 02:06 UTC, Cyma-s requested changes
https://github.com/Neupinion/Neupinion-App/pull/67/files/666c3516aaa6b1a6d157cf7f6c920a615d0df7fc..bd1d472aef5a3774dc3fbab311e9b70679e95bfd#r1546049385

이 부분 리뷰 확인바랍니다!

2024-04-02 02:06 UTC, Cyma-s commented on src/pages/DetailPage.tsx
> +  const id: number = 1;
그리고 `DetailPage` 가 아니라 `ReprocessedIssueDetailPage` 가 되어야 할 것 같네요

2024-04-02 06:36 UTC, hayeounglee commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  const [noOpinion, setNoOpinion] = useState(true);
제가 질문을 잘 이해하지 못해서 질문드립니다.
!myOpinionWrite.length으로 확인하는 방식을 제안하는건가요?
useState를 사용하는 것과 어떤 연관이 있나요...?

2024-04-02 06:38 UTC, hayeounglee commented on src/features/remakeissue/components/ReliabilityEvaluation.tsx
> +  };
이게 put 함수라 remotes에서 관리하는 방법이 떠오르지않아 그랬네요...
바꿔놓도록 하겠습니다!

2024-04-02 07:24 UTC, dmstjdhdh commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  const [noOpinion, setNoOpinion] = useState(true);
질문을 조금 간략화해서 다시 남기겠습니당. myOpinionWrite라는 데이터의 상태(있는지 없는지?) 에 따라서, noOpinion이라는 상수를 업데이트하는 것 같은데, 이런 상수를 사용하지 않고도 개발이 가능해보입니다.

myOpinionWrite.length === 0과 같은 방식을 사용해서 데이터가 있는지 없는지 확인 할 수 있기 때문입니다.

2024-04-02 08:00 UTC, hayeounglee commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  const [noOpinion, setNoOpinion] = useState(true);
넵 이해했습니다. 일단 이 변수 기능에 대해 간단히 설명드리자면,
noOpinion 변수를 통해 북마크 svg가 어떤 상태여야 하는지 결정됩니다. (ex) 북마크가 채워져야 하는지 vs 안채워지는지)
그런데 말씀하신대로 이런 noOpinion 변수를 사용하지 않고 myOpinionWrite.length로 
ui가 어떻게 보여져야 하는지 판단하는게 코드 가독성면에서 떨어지지 않을까 싶습니다...
어떤 의도로 제안해주신건지 나중에 실시간으로 확인하는 것도 좋을 듯 싶습니닷!

2024-04-02 10:59 UTC, dmstjdhdh reviewed
리뷰 답변달았습니다. 확인 부탁드립니다~

2024-04-02 10:59 UTC, dmstjdhdh commented on src/features/remakeissue/components/OpinionWriteSlider.tsx
> +  const [noOpinion, setNoOpinion] = useState(true);
따로 상태를 선언할 때, boolean상태를 다룬다면, is나 has를 사용하는게 좋다고 생각해요. noOpinion이 true이면 Opinion이 없는게 참인지, 부정*긍정을 생각해야하니까 저는 오히려 헷갈리거든요. 제 생각에는 차라리 함수를 만드는게 좋을 것 같아요.

```javascript
function foo(data) {
  if(data.length === 0) return false;
  ...
}
```

이런식을 고려해볼 수 있을 것 같아요. 잘 이해가 가지 않는다면, 나중에 따로 회의요청해주시면 좋겠네요!

2024-04-02 16:53 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNewsItem.tsx
> +}: CategoryLatestNewsSliderItemProps & { category: string }) => {
'동일 카테고리별 재가공 이슈 최신 소식 3개 조회' api에 category 추가를 말하는 건가요?
[
	{
		"id": Long, 재가공 이슈 id,
		"title": String, 재가공 이슈 제목,
		"imageUrl": String, 재가공 이슈 이미지 URL,
		"createdAt": Timestamp, 재가공 이슈 발행일자
                 "category": // 추가
	}
	...
	(최대 3개 제공)
]

2024-04-04 08:33 UTC, hayeounglee commented
- 마크다운 스타일 적용
- 동일카테고리 컴포넌트 props 수정했습니다

확인부탁드립니다:)

2024-04-07 08:47 UTC, Cyma-s approved these changes
상세한 부분은 한 번에 리뷰할게요. 일단은 Approve 하겠습니다!

2024-04-07 10:46 UTC, merged