Feat/#65 ModalProvider 개발 및, dateModal, bottomSheetModal과 같은 Modal 적용 방식 수정
Neupinion/Neupinion-App pull request #69
Opened 2024-03-26 15:29 UTC by dmstjdhdh

## 💬리뷰 참고사항

> 1. Modal과 BottomSheet 관리를 위해 Recoil이라는 상태관리 라이브러리를 추가하였습니다.
> 2. React Native에서 레이어를 따로 관리할 수 있도록 react-native-portalize를 통해 App.tsx에서 Portal을 사용하였습니다. 이를 통해, Global로 관리되는 Modal과 BottomSheet를 제작할 수 있었습니다.

기존의 Modal과 BottomSheet를 관리하는 방식이 변경되어야한다고 생각했습니다. 전역으로 상태관리가 가능한 GlobalModal과 GlobalBottomSheet를 개발하고, 컴포넌트를 Props로 전달하는 방식으로 진행하고자 다음과 같은 리팩토링을 진행하였습니다.

## #️⃣연관된 이슈

> closes #65

2024-03-28 12:33 UTC, Cyma-s requested changes
리뷰 남겼습니닷!

2024-03-30 10:21 UTC, dmstjdhdh commented on src/shared/components/GlobalBottomSheet.tsx
> +const GlobalBottomSheet: React.FC = () => {
BottomSheet와 Modal을 보여주는 방식을 통일하였고, GlobalXXXX의 방식으로 지정한 변수들을 모두 제거했습니다!

2024-03-30 10:22 UTC, dmstjdhdh commented on src/shared/components/GlobalBottomSheet.tsx
> +  };
넵 확인해주셔서 감사합니다!

2024-03-30 10:22 UTC, dmstjdhdh commented on src/shared/hooks/useBottomSheet.ts
> +type UseBottomSheetReturn = {
넵! 해당 타입 사용하지 않게되어 삭제되었지만, 앞으로 타입 지정할때 조심하겠습니다

2024-03-30 10:23 UTC, dmstjdhdh commented on src/shared/hooks/useModal.ts
> +  }, [setModalState]);
넵, Modal이랑 BottomSheet랑 함수 쓰는 방식이 같다보니, 통합하는 것이 더 좋은 방식인 것 같습니다. 반영하였습니다!

2024-03-30 10:23 UTC, dmstjdhdh commented on src/shared/types/bottomSheet.ts
> +export interface BottomSheetState {
넵 제거했습니다!

2024-03-30 11:15 UTC, dmstjdhdh commented
@Cyma-s 이전에 말씀해주신 사항들을 반영하여 코드를 개선해보았습니다.

## 모달 표현 방식
RN에서, 모달을 여러 개를 보여주기 위해서는, 다음과 같은 방식으로 구현해야한다는 것을 알아냈습니다.
```typescript
<ModalA>
   <ModalB/>
</ModalA>
```
따라서, open요청을 받은 Modal들을 Stack의 형태로 보여주는 ModalContainer.tsx를 작성하였습니다. 커스텀 훅인 useModal을 이용해 ModalContainer에 컴포넌트가 전달이 되면, 위에서 보여지는 코드블록처럼 모달을 렌더링하도록 변경하였습니다.

## 모달과 바텀시트 통합
Modal이랑 BottomSheet랑 화면에 나타나는 방식은 같기 때문에, 굳이 구분하지 않고 모두 Modal로 구현하였습니다. 파일 명으로 구분하여 개발 할 예정입니다. 현재 이와같은 방식으로 개발된 모달들은 OpinionWriteBottomSheet, WarningModal, DateModal이 있습니다.

## 애니메이션 관리 방식 변경
dateModalAnimation, bottomSheetAnimation을 확인하시면, Modal이 나타날 때와 사라지기 전의 애니메이션이 정의되어있는걸 확인하실 수 있습니다. 이는, 애니메이션 동작 방식이 컴포넌트 안에서 정의되는것이 가독성이 더 안좋고 재사용성이 낮다는 생각이 들어 개선해보았습니다.

외에도, 피드백주신 내용 (함수 순서, javascript 컨벤션) 을 고려하여 기능들을 재작성하였으니 확인해주시면 감사하겠습니다...!

2024-03-31 05:52 UTC, Cyma-s requested changes
저번보다 코드가 훨씬 깨끗해진 거 같습니다 👍🏻 다만 몇 가지 부분에서 질문이 있어서 한 번만 더 RC 드릴게요 파이팅입니다!

2024-03-31 05:52 UTC, Cyma-s commented on src/features/date/components/DateModal.test.tsx
> +        <DateModal onClose={handleClose} />
👍👍👍

2024-03-31 05:52 UTC, Cyma-s commented on src/features/date/components/DateModal.tsx
> +
코드 너무 깔끔해졌네요 좋아요 👍🏻

2024-03-31 05:52 UTC, Cyma-s commented on src/features/date/constants/calendarTheme.ts
> +const calendarTheme: Theme = {
맨 앞 글자를 소문자로 쓰는 게 컨벤션인가요?

2024-03-31 05:52 UTC, Cyma-s commented on src/features/date/constants/calendarTheme.ts
> +  selectedDayBackgroundColor: '#7E58E9',
추후 이런 색상들도 상수화 되었으면 좋겠습니다

2024-03-31 05:52 UTC, Cyma-s commented on src/features/opinionView/components/OpinionWriteBottomSheet.tsx
> +        onConfirm={() => {}}
여기는 아직 구현이 안 된 부분인가요?

2024-03-31 05:52 UTC, Cyma-s commented on src/features/opinionView/components/OpinionWriteBottomSheet.tsx
> +        if (gestureState.dy > 0 && gestureState.vy > 1.5) {
여기서 1.5 는 따로 추가한 보정 값인가요?

2024-03-31 05:52 UTC, Cyma-s commented on src/pages/DetailPage.tsx
>    };
필요 없는 log 삭제 굿입니다 👍🏻

2024-03-31 05:52 UTC, Cyma-s commented on src/pages/MainPage.tsx
> +  };
log 가 꼭 필요한 부분인가요?

2024-03-31 05:52 UTC, Cyma-s commented on src/recoil/modalState.ts
> +    content: [],
list 로 형이 바뀐 이유는 뭔가요?

2024-03-31 05:52 UTC, Cyma-s commented on src/shared/components/ModalContainer.tsx
> +    null,
여기가 null 인 이유는 뭔가요??

2024-03-31 05:52 UTC, Cyma-s commented on src/shared/components/WarningModal.tsx
> +interface WarningModalProps {
적절하게 이름이 변경되었네요 👍🏻

2024-03-31 05:52 UTC, Cyma-s commented on src/shared/hooks/useModal.ts
> +        content: [...prevState.content, newContent],
prevState.content 에 newContent 를 붙이는 이유가 있나요?

2024-03-31 05:52 UTC, Cyma-s commented on src/Navigation.tsx
> +      <ModalContainer />
이 부분에 넣어도 괜찮은가 보네요 🤔

2024-03-31 11:10 UTC, dmstjdhdh reviewed
리뷰 코멘트 확인했습니다! 몇 부분 수정하였고, 답변 완료했습니다!

2024-03-31 11:10 UTC, dmstjdhdh commented on src/shared/components/ModalContainer.tsx
> +    null,
만약 content에 내용이 실제로 없다면 아무것도 렌더링할 필요가 없기 때문에 null로 초기값을 지정했습니다!

2024-03-31 11:10 UTC, dmstjdhdh commented on src/shared/hooks/useModal.ts
> +        content: [...prevState.content, newContent],
모달을 중복으로 관리할 수 있도록 하기 위해서입니다. A_Modal이 나와있는 상태에서, 그 위에 B_Modal을 띄워주는 요청을 받았을 경우, ModalContainer에서는, B_Modal이 추가된 배열을 받아 화면에 반영합니다. 따라서 newContent가 기존 content상태에 추가됩니다!

2024-03-31 11:25 UTC, Cyma-s approved these changes
처음에 비해 코드가 많이 좋아진 거 같아요 👍🏻👍🏻👍🏻

2024-03-31 11:25 UTC, Cyma-s commented on src/pages/MainPage.tsx
> -
사라진 게 더 낫군요 굿입니다 👍🏻

2024-03-31 11:25 UTC, Cyma-s commented on src/shared/functions/colorWithOpacity.ts
> +export function colorWithOpacity(color: string, opacity: number): string {
함수 따로 정의하니 읽기 쉽네요 👍🏻

2024-03-31 12:31 UTC, hayeounglee approved these changes

2024-03-31 13:41 UTC, merged