Feat/#70 의견쓰기 활동의 api 연동
Neupinion/Neupinion-App pull request #71
Opened 2024-04-02 14:59 UTC by dmstjdhdh

## 💬리뷰 참고사항

> 의견쓰기 활동에서 사용되는 api를 연동하는 작업을 진행하였습니다.
> 의견 포스트잇을 post하는 메서드가 put으로 변경될 예정이며, 이는 아직 반영되지 않았으나, 코드리뷰를 미리 해야 빠른 작업이 진행될 것 같아 PR 올립니다.

1. 원문 보기를 눌렀을 때 나오는 페이지를 구현.
2. 의견 포스트잇을 post하는 기능을 구현 -> put으로 변경 예정
3. 정해진 의견 포스트잇을 삭제하는 기능을 구현 -> #62 브랜치와 연동이 필요합니다. 의견포스트잇을 눌렀을 때, 알맞은 의견 포스트잇의 id와 데이터를 전달받을 수 있도록 개발하였으니, #62 #70 두 브랜치 작업 과정에서 rebase나 새로운 브랜치 작업이 필요합니다.
4. useFetch 커스텀 훅에서, 불필요한 로그 삭제했습니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #70

2024-04-03 09:01 UTC, Cyma-s commented on src/features/opinion/components/SentenceBox.tsx
> +        <Text style={GlobalTextStyles.NormalText17}>ERROR</Text>
지금은 아니더라도 추후 예외 처리가 수행되어야 할 것 같습니다

2024-04-03 09:04 UTC, Cyma-s commented on src/pages/DetailPage.tsx
> +          <TouchableOpacity style={styles.headerSvg} onPress={() => {}}>
여기 onPress 가 사라진 이유가 있나요?

2024-04-03 09:05 UTC, Cyma-s commented on src/pages/DetailPage.tsx
> +        <OpinionWriteSlider navigation={navigation} issueId={1} />
현재는 고정 데이터를 넣고 있는데, 추후 개발될 부분인가욥?

2024-04-03 09:08 UTC, Cyma-s commented on src/pages/OpinionPinPage.tsx
> +          {reprocessedIssue?.content.map((item: ReprocessedIssueContent, index: number) => (
index 를 key 로 사용하는 것은 안티패턴이라고 합니다. 자세한 내용은 [여기](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318)를 참고해주세요. 
백엔드에서 전달할 때 ReprocessedIssueContent 에 id 가 있는 걸로 아는데, key 를 id 로 적용한다면 더 좋을 것 같네요!

2024-04-03 09:10 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +        typeof sentenceIndex === 'number' ? sentenceIndex : 1,
여기 sentenceIndex 를 1로 설정하는 이유는 뭔가요?

2024-04-03 09:18 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +    }
왜 sentenceIndex 를 extract 하는 함수에서 paragraphId 를 리턴하게 되었나요?

2024-04-03 09:19 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +        <TouchableOpacity style={styles.topSvgStyle} onPress={void onClickConfirmButton}>
오잉 이렇게 쓸 수도 있나요?

2024-04-03 09:20 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +            isActivated={sentenceIndex !== undefined}
여기에서 undefined 를 일일이 체크하는 것보다 해당 페이지로 처음 들어왔을 때 수정 요청인지 새롭게 의견을 쓰려고 하는 건지 판단하는 boolean flag 를 하나 두는 게 낫지 않을까요?

2024-04-03 09:21 UTC, Cyma-s commented on src/shared/hooks/useFetch.ts
> +    void fetchData();
깔끔하군요 👍🏻

2024-04-03 14:37 UTC, hayeounglee requested changes
리뷰 확인부탁드립니다!

2024-04-03 14:37 UTC, hayeounglee commented on src/features/remakeissue/remotes/reprocessedissue.ts
>  export const getReprocessedIssues = async (date: string) => {
이 remote 파일에 있는 것들과 제가 만든 remote랑 겹치는 부분이 있어서 나중에 merge할 때 참고하겠습니다..!

2024-04-03 14:37 UTC, hayeounglee commented on src/pages/OpinionPinPage.tsx
> +        <OpinionPinIssue reprocessedIssue={reprocessedIssue} />
이 파일에 작성하지 않고 이렇게 따로 뺀 이유가 있나요?

2024-04-03 14:37 UTC, hayeounglee commented on src/features/opinion/components/OpinionPinIssue.tsx
> +          {reprocessedIssue.tags?.map((item: string, index: number) => (
함수로 tag를 출력하는건가요?
`<Text>{reprocessedIssue.tags}</Text>`와는 뭐가 다른건가요?

2024-04-03 15:54 UTC, dmstjdhdh commented on src/dummy/OpinionWriteDummy.ts
> +  isReliable: true,
그렇네요...! 반영하도록 하겠습니다!

2024-04-03 15:56 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionEvaluateCredibility.tsx
>  interface OpinionEvaluateCredibilityProps {
Reliability로 통일하는게 좋을 것 같습니다~ 전체 변경하겠습니다!

2024-04-03 16:02 UTC, dmstjdhdh commented on src/features/remakeissue/remotes/reprocessedissue.ts
> +import { ReProcessedIssue, ReprocessedIssueId } from "../../../shared/types/news";
못 발견했던건데... 감사합니다!

2024-04-03 16:04 UTC, dmstjdhdh commented on src/pages/DetailPage.tsx
> +          <TouchableOpacity style={styles.headerSvg} onPress={() => {}}>
해당 버튼은, 공유 버튼인데, onClickButton은 아무 기능이 없던 함수였습니다. onClickButton을 없애게 되면서, 공유 버튼에 있던 내용도 사라지게 되었습니다!

2024-04-04 02:56 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +        typeof sentenceIndex === 'number' ? sentenceIndex : 1,
사실 이와 관련해서 고민이 있었습니다. sentenceIndex와, isReliable은 사용자가 아예 선택하지 않은 상태인 undefined라는 상태도 포함됩니다. 하지만 postReprocessedIssueOpinion은, 

```javascript
export const postReprocessedIssueOpinion = async (
  paragraphId: number,
  reprocessedIssueId: number,
  content: string,
  isReliable: boolean,
) => {
  return await client.post('/reprocessed-issue/opinion', {
    paragraphId: paragraphId,
    reprocessedIssueId: reprocessedIssueId,
    content: content,
    isReliable: isReliable,
  });
};
```

이런식으로 number와 boolean타입으로 지정되어있기 때문에, OpinionPostPage에서 관리하는 sentenceIndex와 isReliable이 undefined인 상태일 때의 처리를 1과 true로 임의로 지정하였습니다. 이렇게 임의로 지정하는 방식은 좋지 않은 것 같아, 수정을 하고 싶은데,

OpinionPost에서 사용하는 postReprocessedIssueOpinion을 이렇게 깔끔하게 정리하고 실제 함수는 이렇게 수정해보는건 어떨지 의견을 들어보고 싶습니다...!
```javascript
//OpinionPost에서 사용하는 방식.
const { isLoading, error, fetchData } = useFetch(
    () => postReprocessedIssueOpinion(sentenceIndex, issueId, text, isReliable),
    false,
  );

//변경된 함수
export const postReprocessedIssueOpinion = async (
  paragraphId: number | undefined,
  reprocessedIssueId: number,
  content: string,
  isReliable: boolean | undefined,
) => {
  if (typeof paragraphId !== 'number' && typeof isReliable !== 'boolean') {
    return (오류 처리?);
  }
  return await client.post('/reprocessed-issue/opinion', {
    paragraphId: paragraphId,
    reprocessedIssueId: reprocessedIssueId,
    content: content,
    isReliable: isReliable,
  });
};

```

2024-04-04 02:58 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +    }
만약 바텀시트를 통해서, 의견 수정을 누르면, 본인이 작성한 의견에 맞는 문장을 페이지에서 보여줘야하기 때문입니다!

2024-04-04 03:30 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +        <TouchableOpacity style={styles.topSvgStyle} onPress={void onClickConfirmButton}>
onClickConfirmButton이 비동기함수라서 ESLint에서 void가 return되는 경우를 고려하여 이렇게 작성해야 ESLint 오류가 나지 않더라고요. 찾아보니 버튼이나 이런곳에서 실제로 void를 앞에 붙여서 ESLint 오류를 해결하거나 아예 ESLint 설정을 다음과 같이 하여 문제를 해결하는 경우도 있는 것 같습니다.

```javascript
"rules": {
  "@typescript-eslint/no-misused-promises": [2, {
    "checksVoidReturn": {
      "attributes": false
    }
  }]
},
```

실제로 앞에 void 붙여도 잘 동작합니다!

2024-04-04 03:31 UTC, dmstjdhdh commented on src/features/remakeissue/remotes/reprocessedissue.ts
>  export const getReprocessedIssues = async (date: string) => {
넵넵! 저도 이거 인지하고 있겠습니다. 먼저 merge된 브랜치가 있다면, 그 브랜치를 참고하여 수정하면 좋을 것 같습니다!

2024-04-04 03:34 UTC, dmstjdhdh commented on src/pages/OpinionPinPage.tsx
> +        <OpinionPinIssue reprocessedIssue={reprocessedIssue} />
OpinionPinIssue는, 핀 찍기를 하는 부분 위에 보여지는 기사 컨텐츠입니다(제목, 이미지, 카테고리 등등...). 개발 관심사가 다르다고 생각하여 따로 뺐습니다!

2024-04-04 03:35 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionPinIssue.tsx
> +          {reprocessedIssue.tags?.map((item: string, index: number) => (
tag는 여러개가 가능합니다. 그래서 api를 통해 받아온 reprocessedIssue의tag들을 매핑하여 모두 뿌려줘야 한다고 생각하여 다음과 같이 작성하였습니다. 또한, <View style={styles.tagBox}> 컴포넌트로 감싸줘야 원하는 ui를 만들 수 있어 이렇게 작성했습니다!

2024-04-04 05:06 UTC, Cyma-s commented on src/features/remakeissue/remotes/reprocessedissue.ts
> +import { ReProcessedIssue, ReprocessedIssueId } from "../../../shared/types/news";
eslint 에 등록해두는 게 좋을 것 같습니다

2024-04-04 05:22 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +        typeof sentenceIndex === 'number' ? sentenceIndex : 1,
이 페이지가 수정하기 버튼으로 들어오는지, 의견 등록하기 버튼으로 등록하는지는 알 수 없나요?

2024-04-04 06:10 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +        typeof sentenceIndex === 'number' ? sentenceIndex : 1,
리뷰 코멘트중에, 수정으로 들어오는지 등록으로 들어오는지 구별해주는 flag를 제안해주셨는데, 해당 수정방향으로 고려해서 방안을 모색해보겠습니다!

2024-04-04 06:10 UTC, dmstjdhdh commented on src/features/remakeissue/remotes/reprocessedissue.ts
> +import { ReProcessedIssue, ReprocessedIssueId } from "../../../shared/types/news";
넵넵 감사합니다!

2024-04-04 07:05 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
> +            isActivated={sentenceIndex !== undefined}
덕분에 코드가 더 깔끔해진 것 같습니다. 확인해주실 수 있을까요??

2024-04-04 07:14 UTC, dmstjdhdh reviewed
리뷰사항 반영하였습니다. 금일 저녁 이후에 수정, 등록에 따라서 api를 등록하는 코드를 추가하도록 하겠습니다!

2024-04-04 07:14 UTC, dmstjdhdh commented on src/pages/DetailPage.tsx
> +        <OpinionWriteSlider navigation={navigation} issueId={1} />
넵 하영님께서 개발중이신 부분이랑 연동이 필요하여, 하영님 branch가 merge되면 rebase하여 연동하거나, 새로운 브랜치를 생성해서 개발될 것 같습니다! 아마 스프린트 마무리 단계에서 될 것 같습니다...!

2024-04-04 07:14 UTC, dmstjdhdh commented on src/pages/OpinionPinPage.tsx
> +          {reprocessedIssue?.content.map((item: ReprocessedIssueContent, index: number) => (
그렇겠네요! 데이터의 각 항목의 id를 key로 사용하는 것이 더 좋은 구조라는 것을 알게 되었습니다. 리뷰사항 반영하였습니다. 감사합니다!

2024-04-04 09:53 UTC, Cyma-s requested changes
궁금한 부분 질문 남겼습니다 ;)

2024-04-04 09:53 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
>    }, [route.params]);
`setIsEditMode(!!route.params.opinionWrite);` 도 여기서 초기화될 수 있지 않나요?

2024-04-04 09:53 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +  }, [route.params, isEditMode, isReliable]);
생각해보니 이 부분이 위의 useEffect 보다 먼저 수행되어야 싶은데 어떻게 생각하세요?

2024-04-04 09:53 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +    if (sentenceNumberDefined && isReliableDefined && text.length) {
sentenceNumberDefined 가 true 일 때 isReliableDefined 가 true 가 아닌 경우가 있나요?

2024-04-04 09:53 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
>    }, [route.params]);
extractText 를 위에서 하고 나서 다시 아래에서 수행해줘야 하는건가요?

2024-04-04 11:52 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
>    }, [route.params]);
해당 useEffect 내에서도 초기화될 수 있을 것 같습니다. 하지만 생각해보니, isEditMode가 true인지 false인지는, 컴포넌트가 마운트 될 때만 관리해서 정해버리면 되는 것 같아, 모든 상태들의 초기화 방식을 변경하게 되었습니다.

2024-04-04 11:57 UTC, dmstjdhdh commented on src/pages/OpinionPostPage.tsx
>    }, [route.params]);
다시보니,route.params에 의존하여 초기화되어야하는 경우는 SentenceIndex뿐인 것 같습니다. (핀 찍기 활동 이후 돌아왔을 때에는, 인덱스가 선택되어야하기 때문) 리뷰코멘트 참고하여 반영하여 다시 리뷰 요청드리겠습니다. 감사합니다...!

2024-04-05 02:30 UTC, dmstjdhdh commented
## OpinionPostPage.tsx 변경점

- useEffect 내에서 업데이트가 필요없었던 상태들을 업데이트하고 있던 코드들을 삭제하였습니다.

```javascript
useEffect(() => {
    setSentenceIndex(extractSentenceIndex(route));
    setSentenceNumberDefined(route.params.sentenceNumber !== undefined || isEditMode);
  }, [route.params]);
```

route.params가 변경될 때 마다, SentenceIndex가 변경이 되며, 선택하지 않았다면 defined는 false, 핀 찍기를 통해서 선택되었거나 애초에 수정모드라면 true를 반환하도록 하였습니다.

- EditMode인 flag가 true라면, post가 아닌 patch를 시행하여 기존의 의견 포스트잇을 수정하도록 추가하였습니다.

2024-04-07 06:56 UTC, Cyma-s approved these changes
코드 많이 좋아졌네요. Approve 해도 될 것 같아요

2024-04-07 06:56 UTC, Cyma-s commented on src/pages/OpinionPostPage.tsx
> +        : postReprocessedIssueOpinion(sentenceIndex, issueId, text, isReliable),
삼항연산자 👍🏻

2024-04-07 07:53 UTC, hayeounglee approved these changes

2024-04-07 07:53 UTC, merged