Feat/#76 재가공이슈 투표 페이지 Bubble Chart 개발 및 공통 컴포넌트 개발
Neupinion/Neupinion-App pull request #81
Opened 2024-05-02 04:08 UTC by dmstjdhdh

## 💬리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/95a39fd4-bd89-42f5-828a-9c76764967e5)

## 개발 상태
- 투표 화면에 해당하는 버블차트를 개발하였습니다.
- 버블 차트 하단에 있는, 전체 투표 순위 또한 개발하였습니다.
- Dimension을 통해서 화면의 width와 height를 받아오는 방식을 변경하였습니다. -> WINDOW_WIDTH 상수 사용
- 공통적으로 사용하는 페이지의 헤더의 재사용성을 고려하여 PageHeader 컴포넌트 개발 및 적용을 하였습니다.

## 특이사항
- 투표 화면 하단에 있는, UI들은 해당 브랜치가 병합된 후에 작업 예정입니다.
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/435fa090-098c-4800-bbfc-22eeb931fbe5)

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #76

2024-05-02 10:41 UTC, Cyma-s requested changes
수고하셨습니다! 간단한 질문들만 확인해주세요

2024-05-02 10:41 UTC, Cyma-s commented on src/features/vote/functions/getBubbleFontSize.ts
> +export const getBubbleNameSize = (value: number) => {
유틸 함수로 뺀 거 좋은 것 같네요 👍🏻

2024-05-02 10:41 UTC, Cyma-s commented on src/shared/constants/display.ts
> +export const WINDOW_HEIGHT: number = Dimensions.get('window').height;
적절한 상수화 👍🏻

2024-05-02 11:45 UTC, dmstjdhdh commented on src/features/vote/components/TopOpinionSlider.tsx
> +  if (error || !TopOpinions) {
api반환값이 에러코드일 때, error 상황입니다. TopOpininon이 비어있는 상태와 동일하게 예외 처리를 한 이유는, UI를 어떤식으로 보여줄지 아직 고려된 것이 없어서 동일하게 처리했어요.

그런데 나중에, 두 상황 모두 다르게 처리해야하는 경우를 생각해야하니 지금도 따로 처리하는게 더 좋은 것 같네요...! 변경해놓았습니다!

2024-05-02 12:13 UTC, dmstjdhdh commented on src/features/vote/components/VoteChartContainer.tsx
> +        <BubbleChart height={340} width={WINDOW_WIDTH - 52} data={data.voteRankings} />
현재 버블차트는, SVG 이미지를 height와 width를 받아와서 그에 맞는 크기로 생성하고 있습니다. 

height는 현재 피그마에 있는 버블차트 컴포넌트의 크기를 기준으로 정하였고, 따라서 차트가 UI의 크기와 맞지 않거나 하는 경우는 생기지 않습니다!

2024-05-03 15:06 UTC, hayeounglee commented on src/pages/VoteResultPage.tsx
> +  if (isLoading) {
나중에 로딩, 에러일 때 보여지는 화면을 통일할 필요가 있어 보이네요!

2024-05-03 15:07 UTC, hayeounglee commented on src/pages/VoteResultPage.tsx
> +  if (isLoading) {
저도 나중에 이 코드 참고해서 통일되게 작성해 보겠습니다!

2024-05-03 15:36 UTC, hayeounglee commented on src/dummy/VotedDataDummy.ts
> +      status: '매우 의심',
피그마 UI는 완전 의심인데 확인 부탁드려요!

2024-05-03 15:45 UTC, hayeounglee commented on src/features/vote/components/BubbleChart.tsx
> +  const pack = (data: VoteData[]) =>
이 BubbleChart.tsx가 가장 어려운 코드인 것 같네요🥲
이 pack 변수를 통해 원의 위치를 조정하는 건가요?!

2024-05-03 15:46 UTC, hayeounglee approved these changes

2024-05-04 04:41 UTC, dmstjdhdh commented on src/features/vote/components/BubbleChart.tsx
> +  const pack = (data: VoteData[]) =>
원의 위치는, 아래의 코드를 통해서 bubbleX와 bubbleY에 저장이 됩니다. 해당 코드는 원 자체를 d3라는 라이브러리를 통해서 그려주는 코드라고 생각하시면 좋을 것 같습니다.

```typescript
bubbles.forEach((leaf: d3.HierarchyCircularNode<VoteData>) => {
    const angle = Math.atan2(leaf.y - height / 2, leaf.x - width / 2) + rotationAngle;
    const distance = Math.sqrt((leaf.x - width / 2) ** 2 + (leaf.y - height / 2) ** 2);
    bubbleX.push(width / 2 + Math.cos(angle) * distance);
    bubbleY.push(height / 2 + Math.sin(angle) * distance);
  });
```

2024-05-04 06:47 UTC, hayeounglee commented on src/pages/VoteResultPage.tsx
> +      <PageHeader
중복되는 UI를 Pageheader로 관리하는 거 좋네요👍

2024-05-04 10:20 UTC, Cyma-s approved these changes
수고하셨습니다! 4차 스프린트 가보시죠 💪🏻💪🏻

2024-05-04 10:50 UTC, merged