Feat/#80
Neupinion/Neupinion-App pull request #84
Opened 2024-05-09 03:18 UTC by hayeounglee

## 💬리뷰 참고사항
- DropDown UI 수정해야 할 필요 있음.
- document 참고하고 있으나 피그마에 나와있는 스타일대로 적용이 어려운 상태.
- 아래는 관련 document
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/icons#iconcontainerstyle

## #️⃣연관된 이슈

closes #80

2024-05-09 05:22 UTC, dmstjdhdh requested changes
리뷰 남겼습니다! 반영이 되면, 다시 리뷰 달아보도록 하겠습니다!

2024-05-09 05:22 UTC, dmstjdhdh commented on App.tsx
> +      <OpinionMainPage/>
App.tsx는 기존의 코드로 유지시키면 좋을 것 같아요! 그리고 이 branch가 merge 되었을 때, 투표 페이지에서 navigate 가능하도록 하면 될 것 같습니다.

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +  const mainCategories = ['전체', '문단별 보기'];
상수를 컴포넌트 내에서가 아닌, 분리하여 작성하면 더 좋을 것 같아요!

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +
이곳은 왜 띄워져있는걸까요? Prettier 적용하면 아마 없어질 것 같은데, PR 이전에 ESLint랑, Prettier 적용되었는지 확인해주시면 좋을 것 같습니다!

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +  MainCategoryTop: {
mainCategoryTop이 맞는 것 같습니다!

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +    fontFamily: fontFamily.pretendard.bold,
tag 내에 있는 폰트는 pretendard.medium이 맞는 것 같습니다. 확인 부탁드리겠습니다!

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +    fontFamily: fontFamily.pretendard.bold,
전체적으로 모두 bold 처리 되어있는데, 디자인 확인해주시고, 선택해주시면 좋을 것 같아요!

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +const OpinionMainPage = () => {
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/37d1a9c9-71f9-4bf4-86d1-d2024f7b9fc1)

하단에 적힌 스타일을 봤을때, position이 absolute로 되어있어서, 해상도마다 다르게 하얀색 바가 적용 될 것 같아요. 텍스트의 크기랑 위치를 받아와서 그 밑에 흰색 바를 지정해줘야 할 것 같습니다.

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionPageCategory.tsx
> +        <DropDownPicker
디자인에서는 드랍다운에 외각선이 없습니다! 개발물에서는 나타나고 있어요

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +      <View style={styles.MainCategoryTop}>
ScrollView는 구현 안된걸까요? PageHeader 밑에 보여지는 컴포넌트는 슬라이드가 되어야할 것 같습니다.

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/ParagraphOpinionBigCard.tsx
> +      <View style={{ flexDirection: 'row', marginLeft: 42, marginTop: 10, marginBottom: 30 }}>
텍스트랑, svg 위치가 조금 안 맞는 것 같아요. { flexDirection: 'row', marginLeft: 42, marginTop: 10, marginBottom: 30 } 해당 스타일에 따르면, alignItem이나 justifyContent를 'center'와 같은 속성을 줘야지 정렬이 깔끔하게 되지 않을까 싶습니다.

그리고, style 안에 속성이 조금 많이 들어가게 된다면, 아래 StyleSheet로 작성하는게 더 좋을 것 같아요!

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionPageCategory.tsx
> +const OpinionPageCategory = () => {
실제 화면전환이 이루어지는 페이지는 OpinionMainPage.tsx밖에 없는 것 같은데, 나머지 tsx파일들은, feature에 따로 폴더 생성해서 관리해주시면 좋겠습니다! /src/pages는, 실제 페이지만 작성이 되어야합니다.

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionPageCategory.tsx
> +  ]);
카테고리나, 현재 label value가 있는 객체들은 모두, 상수로 관리되면 좋을 것 같습니다!

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionPageCategory.tsx
> +        <DropDownPicker
DropDownPicker라는 편리한 라이브러리가 있네요. 저도 이거 사용해야겠습니다 :)

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionPageCategory.tsx
> +          style={{
여기에 작성된 스타일도, StyleSheet에 작성이 가능하지 않을까요?

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/OpinionPageCategory.tsx
> +          style={{
arrowIconStyle이랑, dropDownContainerStyle도 마찬가지로요 :)

2024-05-09 05:22 UTC, dmstjdhdh commented on src/pages/ParagraphOpinionPage.tsx
> +const ParagraphOpinionPage = () => {
정확하게는 모르겠지만, ParagraphOpinionPage가 문단의견 페이지가 맞나요? 페이지 단위는 아닌 것 같은데 확인해주시면 좋을 것 같아요.

2024-05-09 14:50 UTC, Cyma-s requested changes
UI 작업 수고하셨습니다 시간 되실 때 리뷰 확인해주세요~

2024-05-09 14:50 UTC, Cyma-s commented on src/pages/OpinionMainPage.tsx
> +            key={index.toString()}
이 부분이 조금 의아하군요 toString 을 해야 했나요?

2024-05-09 14:50 UTC, Cyma-s commented on src/pages/ParagraphOpinionBigCard.tsx
> +      <PinSentenceCard color="#191926" />
여기 색깔도 theme 에 있는 상수 이용할 수 있을 거 같습니다

2024-05-09 14:50 UTC, Cyma-s commented on src/pages/ParagraphOpinionBigCard.tsx
> +    // backgroundColor: theme.color.gray4,
쓰지 않는 주석은 삭제해주세요 🫡

2024-05-09 14:50 UTC, Cyma-s commented on src/pages/TotalOpinionBigCard.tsx
> +const TotalOpinionBigCard = () => {
Big 이라는 형용사는 빼도 될 것 같아요

2024-05-09 14:50 UTC, Cyma-s commented on src/pages/TotalOpinionBigCard.tsx
> +  favoriteText: {
네이밍이 조금 어색한 것 같아요 현재 FE 프로젝트 내에서 favorite 이라고 명칭하고 있는 상태인가요?

2024-05-09 14:50 UTC, Cyma-s commented on src/pages/TotalOpinionBigCard.tsx
> +    backgroundColor: '#1C64ED', // #FF75AB = 의심일 떄
여기 색깔 상수로 관리해주세요

2024-05-09 14:50 UTC, Cyma-s commented on src/pages/TotalOpinionPage.tsx
> +      <View style={styles.headerUnderLine} />
여기 underline 아래에 아무것도 없는 게 맞나요?

2024-05-10 06:05 UTC, hayeounglee commented on src/pages/OpinionMainPage.tsx
> +
Prettier에서 잡고 있지는 않는데 일단 수정하겠습니다!

2024-05-10 06:10 UTC, hayeounglee commented on src/pages/OpinionMainPage.tsx
> +    fontFamily: fontFamily.pretendard.bold,
혹시 이게 피그마에서 bold, medium인지 어떻게 알 수 있나요..?

2024-05-10 07:13 UTC, hayeounglee commented on src/pages/OpinionPageCategory.tsx
> +const OpinionPageCategory = () => {
features/opinon/components에 넣는게 좋을까요?

2024-05-10 07:14 UTC, hayeounglee commented on src/pages/OpinionPageCategory.tsx
> +const OpinionPageCategory = () => {
아니면 따로 다른 파일을 만드는게 좋을까요?!

2024-05-10 07:46 UTC, hayeounglee commented on src/pages/ParagraphOpinionPage.tsx
> +const ParagraphOpinionPage = () => {
TotalOpinionPage,ParagraphOpinionPage
TotalOpinionCategory,ParagraphOpinionCategory로 수정했습니다.!

2024-05-10 08:03 UTC, hayeounglee commented on src/pages/OpinionMainPage.tsx
> +            key={index.toString()}
index의 자료형이 number이고 
key 값의 자료형은 string이여야 해서 형 변환을 했습니다!

2024-05-10 08:04 UTC, hayeounglee commented on src/pages/TotalOpinionPage.tsx
> +      <View style={styles.headerUnderLine} />
넵 없는게 맞습니다!

2024-05-10 09:06 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +    fontFamily: fontFamily.pretendard.bold,
피그마에서 정확하게 나와있지는 않지만, fontWeight가 700~900 이면 bold, 400~600이면 normal이라고 생각하시면 좋을 것 같습니다!

2024-05-10 09:07 UTC, dmstjdhdh commented on src/pages/OpinionPageCategory.tsx
> +const OpinionPageCategory = () => {
아무래도, opinion과 관련된 활동들이 더 많을 것 같아서요, opinion/components/새로운 파일/넣을 파일

구조로 파일을 하나 생성해서 해주시면 어떨까 싶어요! 저도 이후에, 그런 방식으로 다시 파일을 정리해볼게요

2024-05-13 09:07 UTC, hayeounglee commented on src/pages/OpinionPageCategory.tsx
> +const OpinionPageCategory = () => {
넵! OpinionMainPageComponents 새로운 파일을 생성해서 
여기에 관련 component를 관리하도록 수정했습니다!

2024-05-13 09:13 UTC, hayeounglee commented on src/pages/OpinionMainPage.tsx
> +    fontFamily: fontFamily.pretendard.bold,
혹시 말하신 normal이 fontFamily,ts에 medium을 말하는게 맞나요?!
<img width="322" alt="image" src="https://github.com/Neupinion/Neupinion-App/assets/95111439/625e62c0-fea4-41a7-baf2-05fcb7791765">

2024-05-13 09:32 UTC, hayeounglee commented on src/pages/OpinionMainPage.tsx
> +  const mainCategories = ['전체', '문단별 보기'];
넵! constants 디렉토리 아래에 opinionCategory.ts 파일 추가했습니다!

2024-05-13 09:55 UTC, hayeounglee commented on src/pages/TotalOpinionBigCard.tsx
> +  favoriteText: {
피그마에서 svg 명칭을 favorite으로 하고 있어서
해당 text를 favoriteText라고 지정했습니다!
likeText나 다른 네이밍 추천해주면 반영해보겠습니다!

2024-05-14 01:33 UTC, dmstjdhdh commented on src/pages/OpinionMainPage.tsx
> +    fontFamily: fontFamily.pretendard.bold,
아 넵넵 맞습니다!

2024-05-21 04:45 UTC, dmstjdhdh approved these changes
제가 중간에 작업한 부분들이 이 브랜치에 반영되있는 것 같아요. 머지하기 전에, 회의 요청 주시면 좋겠습니다!

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/OpinionSubCategory.tsx
> +  ]);
초기 상태를 상수화 해서 관리해주시면 더 좋을 것 같아요!

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/OpinionSubCategory.tsx
> +  changeRightCategory: (newData: string) => void;
왼쪽, 오른쪽으로 구분되는게 혹시 버튼과, 드롭다운일까요?

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
> +  console.log(item);
기능과 관련이 없는 로그는 지워주시면 좋을 것 같아요!

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
> +    width: Dimensions.get('window').width - 52,
Dimensions.get('window').width를 제가, WINDOW_WIDTH라는 상수로 따로 관리할 수 있도록 코드를 추가하였는데, 해당 상수를 사용해보는건 어떨까요??

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCategory.tsx
> +  // ];
dummy 파일에 따로 작성해주시고, 주석은 없애주시면 좋겠습니다!

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCard.tsx
> +    color: '#E0FFE5',
해당 컬러는, theme.ts파일에서 관리될 수 있지 않을까요?

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCard.tsx
> +    backgroundColor: 'rgba(226, 226, 226, 0.1)',
여기도 마찬가지입니다!

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +  };
이런 함수는, 파일을 생성해서 따로 관리할 수 있을 것 같아요!

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +};
원하는 데이터가 없거나, 크기가 0일 때, EmptyScreen이라는 컴포넌트를 사용하실 수 있을 것 같습니다! (추천)...

2024-05-21 04:45 UTC, dmstjdhdh commented on src/features/totalvote/components/TimeLine.tsx
> +const TimeLine = ({ id }: TimeLineProps) => {
이전에 제가 작업중이던 부분들이 이 브랜치에 반영이 된 것 같아요! 이런 파일들은 병합하기 전에 제거하고 올려주셔야 할 것 같습니다!

2024-05-21 04:45 UTC, dmstjdhdh commented on src/pages/OpinionByParagraphPage.tsx
> +  };
위에서 리뷰한 부분중에서, 이 함수는 중복되는 것 같은데, 확인해주시면 좋을 것 같아요!

2024-05-21 06:45 UTC, hayeounglee commented on src/features/opinion/components/OpinionMainPageComponents/OpinionSubCategory.tsx
> +  changeRightCategory: (newData: string) => void;
넵 맞습니다!

2024-05-21 07:53 UTC, hayeounglee commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
> +    width: Dimensions.get('window').width - 52,
좋습니다!

2024-05-21 17:34 UTC, hayeounglee commented
dropdown 새로운 라이브러리 설치해서
스타일 바꿔놓았습니다!

2024-05-26 09:00 UTC, dmstjdhdh approved these changes
이전에 말씀드린 것 처럼, 머지하기 전에 회의 요청 해주세요. 수고하셨습니다~

2024-05-26 09:35 UTC, Cyma-s requested changes
리뷰 남겼습니다~~ 네이밍 관련 피드백이 많은데 확인해주시면 감사하겠습니다 😄

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/OpinionSubCategory.tsx
> +  changeRightCategory: (newData: string) => void;
rightSubCategory 는 dropdown 이라고 명명하는 게 좋을 거 같아요

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
> +  item: OpinionParagraphId;
이름이 둘이 안 맞는 것 같아요. 적어도 paragraphId 라고 적어주는 게 좋을 것 같네요!

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
> +  };
여기도 Props 이름이 두루뭉술해요

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCategory.tsx
> +  id: number;
무슨 아이디인지 명시해주는 게 좋을 것 같네요 opinionId 같이요

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCategory.tsx
> +            <ParagraphOpinionCard key={item.id} item={item} id={id} />
key item.id 로 설정해준 것 굿입니다 👍🏻

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCard.tsx
> +  item: OpinionTotalId;
여기도요!

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCard.tsx
> +  const [favoriteClicked, setFavoriteClicked] = useState(false);
favorite 보다는 like 라고 많이 씁니다

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCard.tsx
> +  // console.log(item.opinionId);
제거되지 않은 로그!!

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +    { label: '인기순', value: '인기순' },
label, value 모두 필요한 이유가 있나요?

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +  const [rightSubCategory, setRightSubCategory] = useState('');
위에서도 언급했지만 dropdown 이 더 추상화된 이름 같아요

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +  // console.log(opinionTotal);
⚠️

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +            <TouchableOpacity key={index.toString()} onPress={() => handleButtonPress(category)}>
index.toString 보다 category 를 값으로 쓰는 게 낫지 않을까요?

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +  const fetchOpinionTotal = () =>
의견을 추가로 fetch 해오는 기능은 아직 완성이 안 된거죠?

2024-05-26 09:35 UTC, Cyma-s commented on src/features/opinion/remotes/opinion.ts
> +    const payload = { isLiked: !favoriteClicked };
여기서 좋아요 클릭 여부가 변경되는 건 컨텍스트에 맞지 않은 것 같아요
updateFavorite 을 실행하기 전에 favoriteClicked 를 반대로 설정해주면 되지 않을까요?

2024-05-26 09:35 UTC, Cyma-s commented on src/features/vote/components/RelatedIssues.tsx
> +      // </View>
🔍

2024-05-26 09:35 UTC, Cyma-s commented on src/features/vote/components/RelatedIssues.tsx
> +      </View>
에러 화면에서 해당 UI 를 보여주는 걸 의도하신 게 맞을까요?

2024-05-26 09:35 UTC, Cyma-s commented on src/features/vote/components/RelatedIssues.tsx
> +  if (!followUpIssues || followUpIssues.length === 0) {
여기도 동일한 질문입니다!

2024-05-26 09:35 UTC, Cyma-s commented on src/pages/OpinionByParagraphPage.tsx
> +    { label: '최신순', value: '최신순' },
sort 값 데이터는 enum 이나 상수로 관리하는 게 좋을 것 같네요

2024-05-26 09:35 UTC, Cyma-s commented on src/pages/OpinionByParagraphPage.tsx
> +  console.log(opinionParagraph);
로깅!

2024-05-26 09:35 UTC, Cyma-s commented on src/pages/OpinionByParagraphPage.tsx
> +            placeholder="최신순"
이거 필요한가용?

2024-05-26 09:35 UTC, Cyma-s commented on src/pages/OpinionByParagraphPage.tsx
> +    // backgroundColor: theme.color.main,
✏️

2024-05-26 09:35 UTC, Cyma-s commented on src/pages/OpinionMainPage.tsx
> +            key={index.toString()}
category 로 설정해도 될 것 같아요

2024-05-26 09:35 UTC, Cyma-s commented on src/pages/OpinionMainPage.tsx
> +        <TotalOpinionCategory id={1} />
현재는 더미데이터인거죠?

2024-05-26 09:35 UTC, Cyma-s commented on src/shared/components/Opinion/OpinionPaper.tsx
> +    backgroundColor: '#FF75AB',
상수화 필요한 부분입니다!

2024-05-26 09:35 UTC, Cyma-s commented on src/shared/constants/opinionCategory.ts
> +export const getCategoryType = (category: string) => {
너무 추상적인 Category 라는 이름 보다는 ReliableFilter 정도로 구체화해주는 것이 좋을 것 같아요.

2024-05-26 09:35 UTC, Cyma-s commented on src/shared/constants/opinionCategory.ts
> +export const getSortType = (category: string) => {
여기서는 category 가 아닌데 변수를 category 로 받고 있네요. sortType 정도의 이름으로 바꾸는 것이 좋을 것 같습니다.

2024-05-26 09:35 UTC, Cyma-s commented on src/shared/types/news.ts
> +export interface OpinionTotalId {
IntegratedOpinion 정도로 이름을 변경해주는 것이 좋을 것 같습니다.

2024-05-26 09:35 UTC, Cyma-s commented on src/shared/types/news.ts
> +export interface OpinionParagraphId {
interface 이름이 일반적이지 않네요 🤔 ParagraphWithOpinions 가 더 적합한 이름 같습니다

2024-05-26 09:35 UTC, Cyma-s commented on src/shared/types/news.ts
> +export interface Opinions {
s 라는 suffix 는 단 하나의 리스트 객체를 감싸고 있을 때만 사용합니다.
해당 객체는 재가공 이슈의 의견이니 ReprocessedIssueOpinion 로 변경하는 게 좋을 것 같네요.

2024-05-27 00:01 UTC, hayeounglee commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCategory.tsx
> +  id: number;
넵 재가공 이슈 ID 넘겨받는 props의 이름을 issueId로 수정했습니다!

2024-05-27 00:33 UTC, hayeounglee commented on src/pages/OpinionMainPage.tsx
> +        <TotalOpinionCategory id={1} />
재가공 이슈 id 는 임의로 1로 설정했습니다. 
그래서 현재는 api로 받아오는 재가공 이슈의 id는 1이며 나중에 페이지 연동시 바꿔야 할 부분입니다!

2024-05-27 00:44 UTC, hayeounglee commented on src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
> +  };
id를 issueId로 수정했습니다!

2024-05-27 00:49 UTC, hayeounglee commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +            <TouchableOpacity key={index.toString()} onPress={() => handleButtonPress(category)}>
좋은 방법이네요!

2024-05-27 00:53 UTC, hayeounglee commented on src/features/vote/components/RelatedIssues.tsx
> +      // </View>
이건 용우님 파일이여서 나중에 머지할 때 참고하겠습니다!

2024-05-27 01:27 UTC, hayeounglee commented on src/shared/components/Opinion/OpinionPaper.tsx
> +    backgroundColor: '#FF75AB',
용우님 코드여서 나중에 머지할 때 참고하겠습니닷

2024-05-27 01:39 UTC, hayeounglee commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +    { label: '인기순', value: '인기순' },
https://www.npmjs.com/package/react-native-element-dropdown
data props를 보통 label, value와 매치해서 이렇게 작성해보았습니다!

2024-05-27 01:40 UTC, hayeounglee commented on src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
> +  const fetchOpinionTotal = () =>
api로 데이터를 불러오긴합니다!
혹시 '의견을 추가로 fetch'한다는 것에 대해 더 설명해줄 수 있나요?

2024-05-27 01:59 UTC, hayeounglee commented on src/shared/constants/opinionCategory.ts
> +export const getCategoryType = (category: string) => {
이름 추천 감사합니다 :)

2024-05-27 02:18 UTC, hayeounglee commented on src/features/vote/components/RelatedIssues.tsx
> +  if (!followUpIssues || followUpIssues.length === 0) {
@dmstjdhdh

2024-05-27 02:19 UTC, hayeounglee commented on src/features/vote/components/RelatedIssues.tsx
> +      </View>
@dmstjdhdh

2024-05-27 02:33 UTC, hayeounglee commented on src/pages/OpinionByParagraphPage.tsx
> +            placeholder="최신순"
placeholder 가 없으면 'Select item'이 나오기 때문에 필요합니닷!

2024-05-27 02:43 UTC, hayeounglee commented on src/pages/OpinionByParagraphPage.tsx
> +            placeholder="최신순"
발견 감사합니다 삭제했습니다!

2024-05-27 15:33 UTC, closed without merging