Feat/#82 통합 투표 페이지 개발, 투표 페이지 공통 컴포넌트 추가, 수정된 UI 적용
Neupinion/Neupinion-App pull request #86
Opened 2024-05-09 11:23 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 개별 투표 페이지에서 api 연동이 되지 않은 부분은 다음과 같습니다.
- 잘못 적용 되고 있었던 ui의 색을 교체하였습니다.
- 폰트가 적용되지 않고 있던 콘텐츠에 폰트를 적용하였습니다.
- 데이터가 없을 때의 UI를 적용하였습니다.
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/5ad2f465-f4fa-4184-bd0b-5c9bb924d8a0)

- 

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

(close) #이슈번호

2024-05-09 14:43 UTC, Cyma-s requested changes
수고하셨습니다 파일 체인지가 39개네요.. 리뷰 확인해주세요 :-)

2024-05-09 14:43 UTC, Cyma-s commented on src/features/vote/components/RelatedIssues.tsx
> +      ))}
여기는 어떤 부분이 다른가요?

2024-05-09 14:43 UTC, Cyma-s commented on src/features/vote/constants/bubbleColor.ts
> +  '약간 의심': { gradient: 'url(#LittleDoubt)', color: theme.trustColor.littleDoubt },
상수 대체 👍

2024-05-09 14:43 UTC, Cyma-s commented on src/pages/TotalVoteResultPage.tsx
> +            <Text style={styles.rankTitleText}>전체 투표 순위</Text>
나중에 이렇게 중복되는 코드들은 다른 컴포넌트로 분리해도 좋을 듯 합니다

2024-05-09 14:43 UTC, Cyma-s commented on src/pages/VoteResultPage.tsx
> +        <View style={styles.divideLine} />
이 부분도 마찬가지입니다

2024-05-09 14:43 UTC, Cyma-s commented on src/shared/components/FollowUpIssue/FollowUpIssueCardGradient.tsx
> +            </View>
이 부분은 아직 구체적으로 개발은 안 된 상태인가요?

2024-05-09 14:43 UTC, Cyma-s commented on src/shared/styles/theme.ts
> +    BG: '#11111A',
개인적인 생각인데 background 로 풀어서 써도 될 것 같아요
theme 에 있는 color 들 변수 이름도 다 소문자라 BG 가 조금 이질감이 듭니다

2024-05-10 17:46 UTC, dmstjdhdh commented on src/features/vote/components/RelatedIssues.tsx
> +      ))}
api 연동하기 전에 우선은, 피그마에 있는 UI를 띄워주도록 하였습니다. api 연동과 동시에 수정할 예정입니다!

2024-05-10 17:47 UTC, dmstjdhdh commented on src/pages/TotalVoteResultPage.tsx
> +            <Text style={styles.rankTitleText}>전체 투표 순위</Text>
넵 공감합니다...! 통합 투표 api 연동과 함께, 작업해보겠습니다 :):) 👍

2024-05-10 18:01 UTC, dmstjdhdh commented on src/shared/components/FollowUpIssue/FollowUpIssueCardGradient.tsx
> +            </View>
이부분 관련해서, 회의 요청 드리고 싶었습니다! 현재 투표 페이지에 있는 보도가 몇 번째 보도인지 알 수 있는 방법을 어떻게 처리해야할지에 대해서입니다. 곧 회의 요청 드리겠습니다!

2024-05-10 18:03 UTC, dmstjdhdh commented on src/shared/styles/theme.ts
> +    BG: '#11111A',
확실히 그렇습니다...! 피그마에 있는 명명을 그대로 가져왔는데, background가 더 좋을 것 같습니다. 반영하였습니다!

2024-05-14 01:43 UTC, Cyma-s approved these changes
수고하셨습니다!

2024-05-14 01:43 UTC, Cyma-s commented on src/features/vote/components/BubbleChart.tsx
> +import { Circle } from 'react-native-svg';
따로 import 하려고 의도하신건가요?

2024-05-14 01:44 UTC, dmstjdhdh commented on src/features/vote/components/BubbleChart.tsx
> +import { Circle } from 'react-native-svg';
의도한건 아닙니다...! 수정중에 확인했어야하는데, 감사합니다...ㅠㅡㅠ 👍

2024-05-14 02:57 UTC, merged