Bug/#77 의견 쓰기 페이지, 버튼 오류 수정 및 핀 찍기 페이지 이슈 수정
Neupinion/Neupinion-App pull request #88
Opened 2024-05-09 12:22 UTC by dmstjdhdh

## 💬리뷰 참고사항

- 의견 쓰기 페이지 진입시, '믿을 수 있어요' 버튼이 눌리지 않음. '의심이 가요' -> '믿을 수 있어요' 로는 눌려짐 #77 현상을 수정하였습니다.
- 의견 핀 찍기 페이지 진입 시, selected속성이 true인 문장만 보여주고 선택할 수 있도록 수정

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #77 #78

2024-05-09 14:52 UTC, Cyma-s requested changes
간단한 리뷰 하나만 확인해주세요~

2024-05-09 14:52 UTC, Cyma-s commented on src/pages/OpinionPinPage.tsx
> +                  key={index}
index 가 아닌 id 값으로 설정하는 것은 문제가 있을까요?

2024-05-10 17:38 UTC, dmstjdhdh commented on src/pages/OpinionPinPage.tsx
> +                  key={index}
이전에 말씀해 주신 리뷰였던 것 같은데, 다시 확인해주셔서 감사합니다! 다시 변경하여 올렸습니다 :)

2024-05-14 01:59 UTC, hayeounglee approved these changes
수고하셨습니다:)

2024-05-14 02:00 UTC, hayeounglee reviewed
질문 하나 남깁니다!

2024-05-14 02:00 UTC, hayeounglee commented on src/pages/OpinionPinPage.tsx
> +            .filter((item) => item.selected)
filter는 무슨 기능을 하는지 궁금합니다!

2024-05-14 03:31 UTC, dmstjdhdh commented on src/pages/OpinionPinPage.tsx
> +            .filter((item) => item.selected)
item.selected가 true인 배열 값만 추출하는 기능입니다!

2024-05-14 03:32 UTC, dmstjdhdh commented
> 수고하셨습니다:) 궁금한거 질문 하나 남겼습니다!
> 
> 그리고 추가로 혹시 이 브랜치는 sdk 오류가 수정이 된건지 궁금합니다! (expo go 가 실행시 오류가 나서 물어봅니다)

현재 sdk 오류가 수정된 브랜치는 병합된 상태이며, 이 브랜치는 의견쓰기 페이지의 버그만 수정한 페이지입니다!

2024-05-17 08:32 UTC, merged