Feat/#91 투표 페이지 및 통합 투표 페이지 API 연동
Neupinion/Neupinion-App pull request #92
Opened 2024-05-15 09:12 UTC by dmstjdhdh

## 💬리뷰 참고사항

> API 연동은, pages/TotalVoteResultPage, VoteResultPage 모두 진행하였습니다.

- 후속 이슈 슬라이더는, api 연동을 완료한 상태이나, 타임라인 컴포넌트와 같이, 재가공 이슈까지 포함하여 제공해야한다는 내용을 고려하여 이후에 수정이 진행될 것 같습니다.
- 통합 투표 페이지는, 후속 이슈가 존재하지 않으면 넘어가지 않도록 기획서에 정의되어있으나, 후속 이슈 컨텐츠가 아직 제작되어있지 않았고, 넘어가지 않을 때 보여지는 팝업 디자인이 제작되어있지 않았기 때문에 우선 페이지는 이동이 가능한 상태입니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #91

2024-05-16 04:27 UTC, hayeounglee requested changes
리뷰 남겼습니다!

2024-05-16 04:27 UTC, hayeounglee commented on src/shared/functions/getNewsReportOrdinalInKorean.ts
> +export function getNewsReportOrdinalInKorean(num: number): string {
100번째 보도까지는 가지 않을 것 같은데
N번쨰 보도에 대한 표현이 고민 되긴하네요..!

https://npms.io/search?q=%EC%88%AB%EC%9E%90
이런게 있긴한데 보통 서수가 아니라 기수로 나타내긴 하네요

차라리 1th, 2th 같이 영어로 서수를 표현하는 방법은 어떤지 제안해 봅니다..!
https://www.sitepoint.com/convert-numbers-to-ordinals-javascript/

2024-05-16 04:27 UTC, hayeounglee commented on src/features/remakeissue/constants/formatDate.ts
>  export const formatDate = (dateString: string) => {
formatDate, formatMMDD의 이름을 각각 기능에 맞게 바꿔보는게 좋을 것 같아요!

2024-05-16 05:55 UTC, Cyma-s requested changes
리뷰 확인해주세요~

2024-05-16 05:55 UTC, Cyma-s commented on src/shared/functions/getNewsReportOrdinalInKorean.ts
> +export function getNewsReportOrdinalInKorean(num: number): string {
```ts
function numberToKoreanOrdinal(num) {
    const units = ['', '한', '두', '세', '네', '다섯', '여섯', '일곱', '여덟', '아홉'];
    const tens = ['', '열', '스물', '서른', '마흔', '쉰', '예순', '일흔', '여든', '아흔'];
    const suffix = ' 번째';

    if (num === 100) {
        return '백 번째';
    }

    if (num == 1) {
        return '첫 번째';
    }

    const tenPart = Math.floor(num / 10);
    const unitPart = num % 10;

    let koreanNumber = '';

    if (tenPart > 0) {
        koreanNumber += tens[tenPart];
    }
    if (unitPart > 0) {
        koreanNumber += units[unitPart];
    }

    return koreanNumber + suffix;
}
```

이렇게 하면 되지 않을까 합니다.

2024-05-16 07:54 UTC, hayeounglee commented on src/shared/functions/getNewsReportOrdinalInKorean.ts
> +export function getNewsReportOrdinalInKorean(num: number): string {
오오 감탄하고 갑니다👍

2024-05-16 08:25 UTC, dmstjdhdh commented on src/features/remakeissue/constants/formatDate.ts
>  export const formatDate = (dateString: string) => {
넵넵! 기본적으로 year.month.day의 형태로 출력되는 것을 formatDate함수로, year.month로 출력되는 것을 formatDateMMDD로 수정해보았습니다!

2024-05-16 08:32 UTC, dmstjdhdh commented on src/shared/functions/getNewsReportOrdinalInKorean.ts
> +export function getNewsReportOrdinalInKorean(num: number): string {
확인해주셔서 감사해요! 제안해주신 방식 좋네요...

2024-05-16 08:32 UTC, dmstjdhdh commented on src/shared/functions/getNewsReportOrdinalInKorean.ts
> +export function getNewsReportOrdinalInKorean(num: number): string {
제안 감사합니다!

2024-05-17 07:40 UTC, hayeounglee approved these changes

2024-05-17 08:32 UTC, merged