Refactor/#79 재가공이슈 상세페이지 포스트잇 및 투표 컴포넌트 UI 개선 및 바텀시트 UI 개선
Neupinion/Neupinion-App pull request #93
Opened 2024-05-17 09:21 UTC by dmstjdhdh

## 💬리뷰 참고사항

- Before
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/7ffc120f-a291-4549-a6ad-537df657a58e)

- After
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/0172b9c3-f46d-45c5-baec-32c86eb01859)
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/619caa44-5f49-4ebe-bd62-3b9282d9f3db)
![image](https://github.com/Neupinion/Neupinion-App/assets/71542970/5a466865-9a47-4cd5-b470-7993013caeae)

- 포스트잇 내에서 글씨가 넘어가던 문제를 수정하였습니다.
- 잘못 적용된 폰트 스타일을 수정하였습니다.
- 수정된 바텀시트 디자인을 적용하였습니다.
- 카테고리 이슈가 없을 때의 UI를 추가하였습니다.
- 달 이미지가 들어간 투표 UI는 다시 제작이 필요해 보입니다. 비활성화, 활성화 버튼의 스타일이 다르기 때문에, 이후 수정이 필요합니다.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

closes #79

2024-05-19 01:50 UTC, hayeounglee commented
리뷰에 작성하신
달 이미지가 들어간 투표 UI는 다시 제작이 필요해 보입니다. 비활성화, 활성화 버튼의 스타일이 다르기 때문에, 이후 수정이 필요합니다.

부분에서 어떤 스타일 말씀하는건가요?!

2024-05-19 01:55 UTC, hayeounglee requested changes
간단하게 리뷰 남겼습니다 :)

2024-05-19 01:55 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +      {reprocessedIssue && reprocessedIssue.length > 0 ? (
reprocessedIssue.length 을 더 추가한 이유는 무엇인가요?

2024-05-19 01:55 UTC, hayeounglee commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +          <EmptyScreen text={'관련 카테고리 추천 이슈가 없습니다.'} />
자주 쓰일 공통 UI라면 따로 컴포넌트로 빼는거 어떨까요?!

2024-05-19 10:32 UTC, Cyma-s approved these changes
확인했습니다~~

2024-05-21 01:53 UTC, dmstjdhdh commented
> 리뷰에 작성하신 달 이미지가 들어간 투표 UI는 다시 제작이 필요해 보입니다. 비활성화, 활성화 버튼의 스타일이 다르기 때문에, 이후 수정이 필요합니다.
> 
> 부분에서 어떤 스타일 말씀하는건가요?!

미세하지만, 비활성화 일 때와, 활성화 일 때 버튼의 위치가 다른 것 같습니다. 이를 확인하고 수정하고 싶습니다.

2024-05-21 01:55 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +      {reprocessedIssue && reprocessedIssue.length > 0 ? (
원래는 null상태가 아닐 때에만 기존 UI 를 보여줬는데, null이 아닌 []을 받아오는 상황도 처리해주기 위함입니다!

2024-05-21 01:56 UTC, dmstjdhdh commented on src/features/remakeissue/components/CategoryLatestNews.tsx
> +          <EmptyScreen text={'관련 카테고리 추천 이슈가 없습니다.'} />
EmptyScreen 자체가 따로 빼놓은 컴포넌트입니다! import 경로를 확인해주시면 하영님도 다른 곳에서 사용 가능합니다!

2024-05-21 02:02 UTC, hayeounglee approved these changes

2024-05-21 04:46 UTC, merged